/**
 * GENERATED — do not edit. Rewrite it with `pnpm contract:generate`.
 *
 * Printed from social-data's models by `python -m social_data.openapi`. A reading field is present and null
 * where no model has read the post; this file is the only place this app learns that.
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description What `deploy_probe.py` reads to tell this module from another one on the same plan.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Whether the archive can answer at all, which means whether its database can.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ping
         * @description Proves only that the process is up and serving — nothing about its dependencies.
         *
         *     Reads nothing, so Easy Auth can exempt it without exposing anything: `/health` above is
         *     the route that answers whether the database is reachable, and an external prober reading
         *     that would call a healthy process dead the moment one query ran slow.
         */
        get: operations["ping_ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Posts
         * @description A window of posts, newest first.
         *
         *     `hours` is the short way of asking and an explicit range the exact one; both are here because
         *     the screens ask the first and a model asks the second.
         */
        get: operations["posts_posts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{source}/{external_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Post
         * @description One post in full, by the pair that identifies it.
         */
        get: operations["post_posts__source___external_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * State
         * @description What the archive is doing: since when, how recently, and whether a model is configured.
         *
         *     Read before a screen says "no posts", because a quiet source and one that has been unreachable
         *     for three hours produce the same empty window.
         */
        get: operations["state_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail: components["schemas"]["ValidationError"][];
        };
        /** PostOut */
        PostOut: {
            /** Analysed At */
            analysed_at: string | null;
            /**
             * Analysed Model
             * @description which model produced the score and topics — the reading is a fact about what a model said, so it is never published without naming it
             */
            analysed_model: string | null;
            /** Author */
            author: string;
            /**
             * Content
             * @description the post as text, tags removed and entities resolved
             */
            content: string;
            /**
             * External Id
             * @description the identifier that source gave it; unique within it
             */
            external_id: string;
            /**
             * Fetched At
             * Format: date-time
             * @description when this archive first saw it, UTC
             */
            fetched_at: string;
            /**
             * Impact Score
             * @description what a model made of this post's market impact, 1..10 — 1 is noise, 10 a global event
             */
            impact_score: number | null;
            /**
             * Is Repost
             * @description passed on rather than written; descriptive, steers nothing
             * @default false
             */
            is_repost: boolean;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /**
             * Source
             * @description which source this came from — part of the post's identity
             */
            source: string;
            /**
             * Topics
             * @description short topics a model read out of it; empty, never null
             */
            topics: string[];
            /** Translated At */
            translated_at: string | null;
            /**
             * Translated Content
             * @description the Polish reading, or null where no model has produced one
             */
            translated_content: string | null;
            /** Translated Model */
            translated_model: string | null;
            /**
             * Url
             * @description where to read it at the source
             */
            url: string | null;
        };
        /**
         * PostsOut
         * @description A window's answer, with the window it answers for — a list whose edges are implicit is one
         *     the screen has to guess the meaning of.
         */
        PostsOut: {
            /** Count */
            count: number;
            /** Posts */
            posts: components["schemas"]["PostOut"][];
            /**
             * Window From
             * Format: date-time
             */
            window_from: string;
            /**
             * Window To
             * Format: date-time
             */
            window_to: string;
        };
        /**
         * Problem
         * @description One refusal shape for every route, so a consumer handles one thing. `cause` names the layer
         *     that said no: over HTTP a refused request and an empty window otherwise look alike.
         */
        Problem: {
            /**
             * Cause
             * @default module
             * @enum {string}
             */
            cause: "module" | "source" | "request";
            /** Detail */
            detail: string;
            /**
             * Retryable
             * @default false
             */
            retryable: boolean;
        };
        /** SourceStateOut */
        SourceStateOut: {
            /**
             * Collecting Since
             * Format: date-time
             * @description when this archive started collecting the source — there is no backfill, so nothing before this moment is here and never will be
             */
            collecting_since: string;
            /**
             * Consecutive Failures
             * @default 0
             */
            consecutive_failures: number;
            /** Last Failure At */
            last_failure_at: string | null;
            /** Last Failure Reason */
            last_failure_reason: string | null;
            /**
             * Last Success At
             * @description the last pass that reached the source, UTC
             */
            last_success_at: string | null;
            /** Source */
            source: string;
            /**
             * Stale
             * @description the archive has not collected for several intervals; a quiet source and an unreachable one are the same empty list without this
             */
            stale: boolean;
        };
        /**
         * StateOut
         * @description What the archive is doing. Read by both screens before they say "no posts".
         */
        StateOut: {
            /** Collect Interval Seconds */
            collect_interval_seconds: number;
            /**
             * Model Configured
             * @description whether a model is configured at all — false means readings stay empty by configuration, not because nothing was worth reading
             */
            model_configured: boolean;
            /** Posts In Window */
            posts_in_window: number;
            /** Sources */
            sources: components["schemas"]["SourceStateOut"][];
            /** Window Hours */
            window_hours: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx: Record<string, never>;
            /** Input */
            input: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    ping_ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    posts_posts_get: {
        parameters: {
            query?: {
                hours?: number | null;
                since?: string | null;
                until?: string | null;
                source?: string | null;
                min_score?: number | null;
                topic?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostsOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    post_posts__source___external_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source: string;
                external_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    state_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateOut"];
                };
            };
        };
    };
}
