/**
 * GENERATED — do not edit. Rewrite it with `pnpm contract:generate`.
 *
 * Printed from the workbench's conversation surface by `python -m agent.openapi`. The turn's event stream is
 * not in it — OpenAPI does not describe SSE — so `stream.ts` stays hand-written against `agent-chat`.
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chart */
        get: operations["get_chart_chart_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drawings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Drawings */
        get: operations["list_drawings_drawings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drawings/{drawing_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Drawing */
        delete: operations["delete_drawing_drawings__drawing_id__delete"];
        options?: never;
        head?: never;
        /**
         * Patch Drawing
         * @description The correction keeps the drawing's identity: same id, same kind, same instrument,
         *     so a model that read the id before the operator moved the level still points at the
         *     same object (specs/agent-chart-drawings, "Operator cofa rysunek ręką").
         */
        patch: operations["patch_drawing_drawings__drawing_id__patch"];
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prompt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Prompt */
        get: operations["get_prompt_prompt_get"];
        /** Update Prompt */
        put: operations["update_prompt_prompt_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_sessions_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_sessions__session_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Session
         * @description Removes the rozmowa from the operator's history. What it cost stays in the ledger —
         *     see `store.delete_session` for why that is not a compromise but the point.
         */
        delete: operations["delete_session_sessions__session_id__delete"];
        options?: never;
        head?: never;
        /** Patch Session */
        patch: operations["patch_session_sessions__session_id__patch"];
        trace?: never;
    };
    "/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Messages */
        get: operations["get_messages_sessions__session_id__messages_get"];
        put?: never;
        /** Send Message */
        post: operations["send_message_sessions__session_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop Turn
         * @description Ends the turn running in this rozmowa, at the next boundary the graph reaches. `204` whether or not
         *     one was running: a stop arriving a moment late is a race, not a mistake.
         *
         *     The rozmowa is read first, with the owner filter every other route uses, or the registry alone would
         *     tell a stranger whether somebody else's rozmowa is busy.
         */
        post: operations["stop_turn_sessions__session_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/unclaimed-tool-calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Unclaimed Tool Calls
         * @description The calls in this session that no reply ever claimed — sent, and never answered for by a turn that
         *     reached its own end. A route of its own rather than a field on the transcript, whose shape is a list.
         *
         *     Empty for almost every session, and that is the point: a row here is the record of an order whose
         *     fate nobody knows.
         */
        get: operations["get_unclaimed_tool_calls_sessions__session_id__unclaimed_tool_calls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Usage */
        get: operations["get_usage_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChartCommandOut
         * @description What the chart should show now, and the sequence number that says so. Several commands the consumer
         *     missed arrive folded into one, and a field left null by every one of them is still null here.
         */
        ChartCommandOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            focus: components["schemas"]["ChartFocusOut"] | null;
            /** Indicators */
            indicators: components["schemas"]["ChartIndicatorOut"][] | null;
            /** Resolution */
            resolution: string | null;
            /** Sequence */
            sequence: number;
            /** Symbol */
            symbol: string | null;
        };
        /**
         * ChartDrawingOut
         * @description One object standing on an instrument's chart. The geometry is a union discriminated by `kind`, with
         *     each shape's fields named for what they are. No cursor: this is state, read whole and replaced whole.
         */
        ChartDrawingOut: {
            /** Color */
            color: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Geometry */
            geometry: components["schemas"]["ChartLevelOut"] | components["schemas"]["ChartZoneOut"] | components["schemas"]["ChartTrendlineOut"];
            /** Hidden */
            hidden: boolean;
            /** Id */
            id: number;
            /** Label */
            label: string | null;
            /** Symbol */
            symbol: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ChartFocusOut */
        ChartFocusOut: {
            /** Around */
            around: string | null;
            /** Bars */
            bars: number | null;
            /** From */
            from: string | null;
            /** Last Bars */
            last_bars: number | null;
            /** To */
            to: string | null;
        };
        /** ChartIndicatorIn */
        ChartIndicatorIn: {
            /** Color */
            color?: string | null;
            /** Id */
            id: string;
            /** Params */
            params?: {
                [key: string]: number;
            };
        };
        /** ChartIndicatorOut */
        ChartIndicatorOut: {
            /** Color */
            color: string | null;
            /** Id */
            id: string;
            /** Params */
            params: {
                [key: string]: number;
            };
        };
        /** ChartLevelOut */
        ChartLevelOut: {
            /** At */
            at: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "level";
            /** Price */
            price: number;
        };
        /** ChartPointOut */
        ChartPointOut: {
            /** Price */
            price: number;
            /**
             * Time
             * Format: date-time
             */
            time: string;
        };
        /**
         * ChartSnapshotIn
         * @description What the caller is drawing right now. Optional everywhere: a consumer without a chart has nothing
         *     to send, and a turn without this behaves exactly as it did before the field existed.
         */
        ChartSnapshotIn: {
            /** Indicators */
            indicators?: components["schemas"]["ChartIndicatorIn"][];
            /** Resolution */
            resolution?: string | null;
            /** Symbol */
            symbol?: string | null;
            /** Visible From */
            visible_from?: string | null;
            /** Visible To */
            visible_to?: string | null;
        };
        /** ChartTrendlineOut */
        ChartTrendlineOut: {
            a: components["schemas"]["ChartPointOut"];
            b: components["schemas"]["ChartPointOut"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "trendline";
        };
        /** ChartZoneOut */
        ChartZoneOut: {
            /** Bottom */
            bottom: number;
            /** From */
            from: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "zone";
            /** To */
            to: string | null;
            /** Top */
            top: number;
        };
        /** CreateSessionIn */
        CreateSessionIn: {
            /** Model Id */
            model_id?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail: components["schemas"]["ValidationError"][];
        };
        /** MessageOut */
        MessageOut: {
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Incomplete */
            incomplete: boolean;
            /** Model Id */
            model_id: string | null;
            /** Prompt Version */
            prompt_version: string | null;
            /** Role */
            role: string;
            /** Stopped */
            stopped: boolean;
            /** Tool Calls */
            tool_calls: components["schemas"]["ToolCallOut"][];
        };
        /** ModelOut */
        ModelOut: {
            /** Cost Rank */
            cost_rank: number;
            /** Display Name */
            display_name: string;
            /** Id */
            id: string;
            /** Input Rate Per 1M */
            input_rate_per_1m: string;
            /** Output Rate Per 1M */
            output_rate_per_1m: string;
        };
        /**
         * PatchDrawingIn
         * @description What the operator may correct by hand: the prices and the caption. Not `kind` and not `symbol` — a
         *     level that became a zone is a different drawing. One field per price *role*, not per column.
         */
        PatchDrawingIn: {
            /**
             * A Price
             * @description a trend line's first price
             */
            a_price?: number | null;
            /**
             * B Price
             * @description a trend line's second price
             */
            b_price?: number | null;
            /**
             * Bottom
             * @description a zone's lower price
             */
            bottom?: number | null;
            /** Hidden */
            hidden?: boolean | null;
            /** Label */
            label?: string | null;
            /**
             * Price
             * @description a level's price
             */
            price?: number | null;
            /**
             * Top
             * @description a zone's upper price
             */
            top?: number | null;
        };
        /**
         * PatchSessionIn
         * @description Both fields optional, at least one required — one route for two edits an operator makes at
         *     different moments and never together.
         */
        PatchSessionIn: {
            /** Model Id */
            model_id?: string | null;
            /** Title */
            title?: string | null;
        };
        /** PromptOut */
        PromptOut: {
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: string;
            /** With Tools */
            with_tools: string;
            /** Without Tools */
            without_tools: string;
        };
        /** PromptUpdateIn */
        PromptUpdateIn: {
            /** With Tools */
            with_tools: string;
            /** Without Tools */
            without_tools: string;
        };
        /** SendMessageIn */
        SendMessageIn: {
            /** @description what the caller is drawing as it asks; given to the model as context for this turn only, never written to the transcript */
            chart?: components["schemas"]["ChartSnapshotIn"] | null;
            /** Content */
            content: string;
        };
        /** SessionOut */
        SessionOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Model Id */
            current_model_id: string;
            /** Id */
            id: number;
            /**
             * Last Active At
             * Format: date-time
             */
            last_active_at: string;
            /** Title */
            title: string | null;
        };
        /**
         * ToolCallOut
         * @description One tool call, published in exactly one shape whether it leaves as a stream event or hangs off a reloaded
         *     transcript. No `id` and no `created_at`: the live event has neither, and a field one path cannot fill is unreliable.
         */
        ToolCallOut: {
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Duration Ms */
            duration_ms: number;
            /**
             * Outcome
             * @example ok
             * @example refused
             * @example unavailable
             * @example unknown
             */
            outcome: string;
            /** Position */
            position: number;
            /** Result Text */
            result_text: string;
            /** Round Index */
            round_index: number;
            /**
             * Source
             * @example server
             * @example module
             */
            source: string;
            /** Tool Name */
            tool_name: string;
        };
        /** UsageAggregateOut */
        UsageAggregateOut: {
            /** Cost */
            cost: string;
            /** Input Tokens */
            input_tokens: number;
            /** Key */
            key: string;
            /** Output Tokens */
            output_tokens: number;
            /** Unknown Count */
            unknown_count: number;
        };
        /** UsageSummaryOut */
        UsageSummaryOut: {
            /** By Day */
            by_day: components["schemas"]["UsageAggregateOut"][];
            /** By Model */
            by_model: components["schemas"]["UsageAggregateOut"][];
            /** By Session */
            by_session: components["schemas"]["UsageAggregateOut"][];
            /** Total Cost */
            total_cost: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx: Record<string, never>;
            /** Input */
            input: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_chart_chart_get: {
        parameters: {
            query?: {
                /** @description the sequence number the caller has already applied; 0 asks for the whole standing state */
                after?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartCommandOut"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_drawings_drawings_get: {
        parameters: {
            query: {
                /** @description the instrument whose drawings to read, e.g. US100 */
                symbol: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartDrawingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_drawing_drawings__drawing_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                drawing_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_drawing_drawings__drawing_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                drawing_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchDrawingIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartDrawingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelOut"][];
                };
            };
        };
    };
    get_prompt_prompt_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptOut"];
                };
            };
        };
    };
    update_prompt_prompt_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"][];
                };
            };
        };
    };
    create_session_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_session_sessions__session_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchSessionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_messages_sessions__session_id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_sessions__session_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_turn_sessions__session_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_unclaimed_tool_calls_sessions__session_id__unclaimed_tool_calls_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolCallOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_usage_usage_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
