/**
 * GENERATED — do not edit. Rewrite it with \`pnpm contract:generate\`.
 *
 * The source is the strategy platform's own OpenAPI document, printed straight from its
 * Pydantic models by \`python -m strategy.openapi\`.
 *
 * Most of what this contract describes is a **refusal**: a decision carrying a reason and
 * no levels. \`reason_kind\` says which layer said no — the strategy, a gap in the data,
 * or a platform limit — and the three have different answers, so a consumer that collapses
 * them has thrown away the part worth reading.
 *
 * Every optional field on a response is generated as \`T | null\` rather than
 * \`T | undefined\`: this module answers with the whole model, and a stop that is absent
 * is a stop that was never set, not a field that failed to arrive.
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Backtests */
        get: operations["list_backtests_backtests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtests/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Backtest */
        get: operations["read_backtest_backtests__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Decisions
         * @description Newest first, with the reason on every row.
         *
         *     The refusals are the ordinary case and are not filtered out by default: "the system has
         *     not traded in three weeks" is answered by reading them, and a list that showed only
         *     setups would answer it with silence.
         */
        get: operations["list_decisions_decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decisions/{decision_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Decision
         * @description One decision with the readings it stood on — enough to re-decide it offline.
         */
        get: operations["read_decision_decisions__decision_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Whether the platform can answer at all, which means whether its database can.
         *
         *     `watching` is a count and never a requirement: zero is a supported state, not a
         *     degraded one (`strategy-runtime`, "Platforma bez strategii jest stanem wspieranym").
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parameter-sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Parameter Sets */
        get: operations["list_parameter_sets_parameter_sets_get"];
        put?: never;
        /**
         * Add Parameter Set
         * @description Write the next version of a strategy's parameters.
         *
         *     Resolved before it is stored — defaults filled in, every value checked against its
         *     declared range — so what is written down is what would be used, not what was typed. A
         *     value out of range is refused here rather than discovered at the next evaluation.
         */
        post: operations["add_parameter_set_parameter_sets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ping
         * @description Proves only that the process is up and serving — nothing about its dependencies.
         *
         *     Reads nothing: `/health` above already answers whether the database is reachable, and
         *     an external prober checking that would read a healthy process as dead the moment a
         *     query ran slow. This is what Easy Auth's `excluded_paths` can exempt without exposing
         *     anything — the response never varies with this module's state.
         */
        get: operations["ping_ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Strategies
         * @description Every strategy this image carries. Read from the catalogue, never from a table —
         *     the entries are code, and a row claiming otherwise would be a second truth.
         */
        get: operations["list_strategies_strategies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies/{strategy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Strategy */
        get: operations["read_strategy_strategies__strategy_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Watches */
        get: operations["list_watches_watches_get"];
        put?: never;
        /**
         * Put Watch
         * @description Start watching a pair with a strategy.
         *
         *     **This is where a strategy is registered**, and where its facts are checked against
         *     what the archive actually announces. The check is made here rather than at import
         *     because the answer can only be had by asking — and an archive that cannot be asked
         *     means the registration is refused, not that it is waved through: registering a
         *     strategy whose facts may not exist is how a platform ends up watching nothing and
         *     saying nothing.
         */
        post: operations["put_watch_watches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watches/{watch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set Watch Active
         * @description The whole of the off switch. Deactivating one watch leaves every other running, and
         *     is the way back out of a strategy — no deployment, no restart.
         */
        patch: operations["set_watch_active_watches__watch_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BacktestRunOut
         * @description One kept report. The three fields before `report` are the ones two runs must share
         *     before their numbers may be read together — as fields rather than only inside the
         *     blob, so a caller can check that without parsing it.
         */
        BacktestRunOut: {
            /** Costs */
            costs: {
                [key: string]: number;
            };
            /** Id */
            id: number;
            /** Params */
            params: {
                [key: string]: number;
            };
            /**
             * Ran At
             * Format: date-time
             */
            ran_at: string;
            /**
             * Range From
             * Format: date-time
             */
            range_from: string;
            /**
             * Range To
             * Format: date-time
             */
            range_to: string;
            /** Report */
            report: {
                [key: string]: unknown;
            };
            /** Resolution */
            resolution: string;
            /** Strategy Id */
            strategy_id: string;
            /** Symbol */
            symbol: string;
        };
        /**
         * DecisionDetailOut
         * @description One decision with the readings it stood on — enough to re-decide it without the
         *     archive, which is what makes a recorded decision evidence rather than an anecdote.
         */
        DecisionDetailOut: {
            /**
             * Action
             * @enum {string}
             */
            action: "trade" | "no_trade";
            /**
             * As Of
             * Format: date-time
             * @description the closing time of the bar decided on, never a wall clock
             */
            as_of: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Direction */
            direction: ("long" | "short") | null;
            /** Entry */
            entry: number | null;
            /**
             * Facts
             * @description the snapshot `evaluate` was handed
             */
            facts: {
                [key: string]: unknown;
            };
            /**
             * Features
             * @description what the strategy measured, named
             */
            features: {
                [key: string]: number;
            };
            /** Id */
            id: number;
            /**
             * Parameter Set Id
             * @description which version of the parameters decided this
             */
            parameter_set_id: number;
            /** Reason */
            reason: string | null;
            /**
             * Reason Kind
             * @description which layer refused: the strategy itself, a gap in the data, or a platform limit. A gap is answered by fetching history; the strategy's own no is answered by reading the strategy
             */
            reason_kind: ("strategy" | "coverage" | "limit") | null;
            /**
             * Rr
             * @description reward over risk, from the levels
             */
            rr: number | null;
            /** Score */
            score: number | null;
            /** Stop */
            stop: number | null;
            /** Strategy Id */
            strategy_id: string;
            /** Symbol */
            symbol: string;
            /** Target */
            target: number | null;
        };
        /** DecisionOut */
        DecisionOut: {
            /**
             * Action
             * @enum {string}
             */
            action: "trade" | "no_trade";
            /**
             * As Of
             * Format: date-time
             * @description the closing time of the bar decided on, never a wall clock
             */
            as_of: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Direction */
            direction: ("long" | "short") | null;
            /** Entry */
            entry: number | null;
            /**
             * Features
             * @description what the strategy measured, named
             */
            features: {
                [key: string]: number;
            };
            /** Id */
            id: number;
            /**
             * Parameter Set Id
             * @description which version of the parameters decided this
             */
            parameter_set_id: number;
            /** Reason */
            reason: string | null;
            /**
             * Reason Kind
             * @description which layer refused: the strategy itself, a gap in the data, or a platform limit. A gap is answered by fetching history; the strategy's own no is answered by reading the strategy
             */
            reason_kind: ("strategy" | "coverage" | "limit") | null;
            /**
             * Rr
             * @description reward over risk, from the levels
             */
            rr: number | null;
            /** Score */
            score: number | null;
            /** Stop */
            stop: number | null;
            /** Strategy Id */
            strategy_id: string;
            /** Symbol */
            symbol: string;
            /** Target */
            target: number | null;
        };
        /** FactOut */
        FactOut: {
            /** Bars */
            bars: number;
            /**
             * Indicator
             * @description the archive's catalogue id
             */
            indicator: string;
            /**
             * Key
             * @description what the strategy reads this back under
             */
            key: string;
            /**
             * Params
             * @description a string names one of this strategy's own parameters
             */
            params: {
                [key: string]: number | string;
            };
            /** Resolution */
            resolution: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail: components["schemas"]["ValidationError"][];
        };
        /** ParamOut */
        ParamOut: {
            /** Default */
            default: number;
            /** Max */
            max: number;
            /** Min */
            min: number;
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "int" | "float";
        };
        /** ParameterSetIn */
        ParameterSetIn: {
            /**
             * Params
             * @description defaults are filled in for anything omitted
             */
            params?: {
                [key: string]: number;
            };
            /** Strategy Id */
            strategy_id: string;
        };
        /** ParameterSetOut */
        ParameterSetOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /**
             * Params
             * @description resolved — defaults filled in
             */
            params: {
                [key: string]: number;
            };
            /** Strategy Id */
            strategy_id: string;
            /**
             * Version
             * @description append-only; a change of mind is the next version
             */
            version: number;
        };
        /**
         * StrategyOut
         * @description One catalogue entry as it can be read from outside — everything but its function.
         */
        StrategyOut: {
            /** Candles */
            candles: number;
            /** Description */
            description: string;
            /** Facts */
            facts: components["schemas"]["FactOut"][];
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Params */
            params: components["schemas"]["ParamOut"][];
            /**
             * Resolution
             * @description the bars whose closes drive evaluation
             */
            resolution: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx: Record<string, never>;
            /** Input */
            input: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WatchIn */
        WatchIn: {
            /**
             * Parameter Set Id
             * @description omit to have a set written from this strategy's defaults
             */
            parameter_set_id?: number | null;
            /** Strategy Id */
            strategy_id: string;
            /** Symbol */
            symbol: string;
        };
        /** WatchOut */
        WatchOut: {
            /** Active */
            active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Parameter Set Id */
            parameter_set_id: number;
            /** Strategy Id */
            strategy_id: string;
            /** Symbol */
            symbol: string;
        };
        /** WatchPatch */
        WatchPatch: {
            /** Active */
            active: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_backtests_backtests_get: {
        parameters: {
            query?: {
                strategy_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_backtest_backtests__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_decisions_decisions_get: {
        parameters: {
            query?: {
                strategy_id?: string | null;
                symbol?: string | null;
                action?: ("trade" | "no_trade") | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_decision_decisions__decision_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                decision_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_parameter_sets_parameter_sets_get: {
        parameters: {
            query?: {
                strategy_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParameterSetOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_parameter_set_parameter_sets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParameterSetIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParameterSetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ping_ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_strategies_strategies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyOut"][];
                };
            };
        };
    };
    read_strategy_strategies__strategy_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_watches_watches_get: {
        parameters: {
            query?: {
                active_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_watch_watches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_watch_active_watches__watch_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watch_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
