/**
 * GENERATED — do not edit. Rewrite it with `pnpm contract:generate`.
 *
 * Printed from the strategy platform's models by `python -m strategy.openapi`. Most of what it describes is
 * a refusal: `reason_kind` names the layer that said no, and an optional field is `T | null`, never absent.
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Backtests */
        get: operations["list_backtests_backtests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtests/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Backtest */
        get: operations["read_backtest_backtests__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Decisions
         * @description Newest first, with the reason on every row.
         *
         *     The refusals are the ordinary case and are not filtered out by default: "the system has
         *     not traded in three weeks" is answered by reading them, and a list that showed only
         *     setups would answer it with silence.
         */
        get: operations["list_decisions_decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decisions/{decision_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Decision
         * @description One decision with the readings it stood on — enough to re-decide it offline.
         */
        get: operations["read_decision_decisions__decision_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Definitions
         * @description Every rule that was written down. The coded entries are not here — they are in
         *     `/strategies`, which lists both, and this route is about what can be edited.
         */
        get: operations["list_definitions_definitions_get"];
        put?: never;
        /**
         * Add Definition
         * @description A new rule and its first revision.
         *
         *     Answers with the revision rather than the definition, because the revision is the thing
         *     anything else points at: a watch pins one, a decision names one, and a caller that got
         *     only the definition back would have to ask again to do anything with it.
         */
        post: operations["add_definition_definitions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/definitions/{strategy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Definition */
        get: operations["read_definition_definitions__strategy_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Rename Definition
         * @description The title and the sentence under it — never the rule.
         *
         *     Editing the rule is a new revision, and this route deliberately cannot do it: a title
         *     fixed in place must not change what any recorded decision points at.
         */
        patch: operations["rename_definition_definitions__strategy_id__patch"];
        trace?: never;
    };
    "/definitions/{strategy_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Revisions
         * @description Newest first. Nothing is ever removed from this list.
         */
        get: operations["list_revisions_definitions__strategy_id__revisions_get"];
        put?: never;
        /**
         * Add Revision
         * @description The next revision. The previous one stays exactly as it was, and so do its watches.
         */
        post: operations["add_revision_definitions__strategy_id__revisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/definitions/{strategy_id}/revisions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Revision
         * @description One numbered revision, in the wording it had when it was written.
         */
        get: operations["read_revision_definitions__strategy_id__revisions__version__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Whether the platform can answer at all, which means whether its database can.
         *
         *     `watching` is a count and never a requirement: zero is a supported state, not a
         *     degraded one (`strategy-runtime`, "Platforma bez strategii jest stanem wspieranym").
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parameter-sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Parameter Sets */
        get: operations["list_parameter_sets_parameter_sets_get"];
        put?: never;
        /**
         * Add Parameter Set
         * @description Write the next version of a strategy's parameters.
         *
         *     Resolved before it is stored — defaults filled in, every value checked against its
         *     declared range — so what is written down is what would be used, not what was typed. A
         *     value out of range is refused here rather than discovered at the next evaluation.
         *
         *     The set is stamped with the revision whose declaration it satisfied. Which ranges a set
         *     was checked against is a fact about the moment it was written, and one revision later it
         *     may not be true any more (design.md, decision 6).
         */
        post: operations["add_parameter_set_parameter_sets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ping
         * @description Proves only that the process is up and serving — nothing about its dependencies.
         *
         *     Reads nothing: `/health` above already answers whether the database is reachable, and
         *     an external prober checking that would read a healthy process as dead the moment a
         *     query ran slow. This is what Easy Auth's `excluded_paths` can exempt without exposing
         *     anything — the response never varies with this module's state.
         */
        get: operations["ping_ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Strategies
         * @description Every strategy this platform can run: the image's entries and the written rules.
         *
         *     One list rather than two, because everything downstream treats them identically and a
         *     screen that had to merge two lists would be the first place the distinction leaked.
         */
        get: operations["list_strategies_strategies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies/{strategy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Strategy
         * @description One strategy, at a named revision or at its newest.
         *
         *     `revision` on a coded entry is refused rather than ignored: it is a caller believing
         *     something untrue about which kind of strategy this is.
         */
        get: operations["read_strategy_strategies__strategy_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Watches */
        get: operations["list_watches_watches_get"];
        put?: never;
        /**
         * Put Watch
         * @description Start watching a pair with a strategy, or move an existing watch.
         *
         *     **This is where a strategy is registered**, and where its facts are checked against
         *     what the archive actually announces. The check is made here rather than at import
         *     because the answer can only be had by asking — and an archive that cannot be asked
         *     means the registration is refused, not that it is waved through: registering a
         *     strategy whose facts may not exist is how a platform ends up watching nothing and
         *     saying nothing. It stays here even though a written rule was already checked when it was
         *     saved: the archive's catalogue can change in between, and this is the check that guards
         *     the loop (design.md, decision 8).
         *
         *     **The revision is pinned, not followed.** Omitting `revision` pins the newest at this
         *     moment; a revision written afterwards changes nothing about this watch until somebody
         *     calls here again.
         */
        post: operations["put_watch_watches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watches/{watch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set Watch Active
         * @description The whole of the off switch. Deactivating one watch leaves every other running, and
         *     is the way back out of a strategy — no deployment, no restart.
         */
        patch: operations["set_watch_active_watches__watch_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Arith */
        "Arith-Input": {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "arith";
            /**
             * Op
             * @enum {string}
             */
            op: "+" | "-" | "*" | "/";
            /** Operands */
            operands: (components["schemas"]["Const"] | components["schemas"]["ParamRef"] | components["schemas"]["FactRead"] | components["schemas"]["BarRead"] | components["schemas"]["Arith-Input"] | components["schemas"]["Call-Input"] | components["schemas"]["Previous-Input"])[];
        };
        /** Arith */
        "Arith-Output": {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "arith";
            /**
             * Op
             * @enum {string}
             */
            op: "+" | "-" | "*" | "/";
            /** Operands */
            operands: (components["schemas"]["Const"] | components["schemas"]["ParamRef"] | components["schemas"]["FactRead"] | components["schemas"]["BarRead"] | components["schemas"]["Arith-Output"] | components["schemas"]["Call-Output"] | components["schemas"]["Previous-Output"])[];
        };
        /**
         * BacktestRunOut
         * @description One kept report. The three fields before `report` are the ones two runs must share before their
         *     numbers may be read together — as fields, so a caller can check that without parsing the blob.
         */
        BacktestRunOut: {
            /** Costs */
            costs: {
                [key: string]: number;
            };
            /** Id */
            id: number;
            /** Params */
            params: {
                [key: string]: number;
            };
            /**
             * Ran At
             * Format: date-time
             */
            ran_at: string;
            /**
             * Range From
             * Format: date-time
             */
            range_from: string;
            /**
             * Range To
             * Format: date-time
             */
            range_to: string;
            /** Report */
            report: {
                [key: string]: unknown;
            };
            /** Resolution */
            resolution: string;
            /** Strategy Id */
            strategy_id: string;
            /**
             * Strategy Revision Id
             * @description the revision this run computed; null for a coded entry
             */
            strategy_revision_id: number | null;
            /** Symbol */
            symbol: string;
        };
        /** BarRead */
        BarRead: {
            /**
             * Field
             * @default close
             * @enum {string}
             */
            field: "open" | "high" | "low" | "close";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "bar";
            /**
             * Offset
             * @default 0
             */
            offset: number;
        };
        /** Call */
        "Call-Input": {
            /**
             * Fn
             * @enum {string}
             */
            fn: "abs" | "min" | "max" | "round";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "call";
            /** Operands */
            operands: (components["schemas"]["Const"] | components["schemas"]["ParamRef"] | components["schemas"]["FactRead"] | components["schemas"]["BarRead"] | components["schemas"]["Arith-Input"] | components["schemas"]["Call-Input"] | components["schemas"]["Previous-Input"])[];
        };
        /** Call */
        "Call-Output": {
            /**
             * Fn
             * @enum {string}
             */
            fn: "abs" | "min" | "max" | "round";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "call";
            /** Operands */
            operands: (components["schemas"]["Const"] | components["schemas"]["ParamRef"] | components["schemas"]["FactRead"] | components["schemas"]["BarRead"] | components["schemas"]["Arith-Output"] | components["schemas"]["Call-Output"] | components["schemas"]["Previous-Output"])[];
        };
        /** Compare */
        "Compare-Input": {
            /** Left */
            left: components["schemas"]["Const"] | components["schemas"]["ParamRef"] | components["schemas"]["FactRead"] | components["schemas"]["BarRead"] | components["schemas"]["Arith-Input"] | components["schemas"]["Call-Input"] | components["schemas"]["Previous-Input"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "compare";
            /**
             * Op
             * @enum {string}
             */
            op: "<" | "<=" | ">" | ">=";
            /** Right */
            right: components["schemas"]["Const"] | components["schemas"]["ParamRef"] | components["schemas"]["FactRead"] | components["schemas"]["BarRead"] | components["schemas"]["Arith-Input"] | components["schemas"]["Call-Input"] | components["schemas"]["Previous-Input"];
        };
        /** Compare */
        "Compare-Output": {
            /** Left */
            left: components["schemas"]["Const"] | components["schemas"]["ParamRef"] | components["schemas"]["FactRead"] | components["schemas"]["BarRead"] | components["schemas"]["Arith-Output"] | components["schemas"]["Call-Output"] | components["schemas"]["Previous-Output"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "compare";
            /**
             * Op
             * @enum {string}
             */
            op: "<" | "<=" | ">" | ">=";
            /** Right */
            right: components["schemas"]["Const"] | components["schemas"]["ParamRef"] | components["schemas"]["FactRead"] | components["schemas"]["BarRead"] | components["schemas"]["Arith-Output"] | components["schemas"]["Call-Output"] | components["schemas"]["Previous-Output"];
        };
        /** Const */
        Const: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "const";
            /** Value */
            value: number;
        };
        /**
         * Crossed
         * @description Two expressions crossing on this bar — the one piece of sugar in the vocabulary. A crossing expressed
         *     as four comparisons over two frames is four places for one of them to drift.
         */
        "Crossed-Input": {
            /**
             * Direction
             * @enum {string}
             */
            direction: "above" | "below";
            /** Left */
            left: components["schemas"]["Const"] | components["schemas"]["ParamRef"] | components["schemas"]["FactRead"] | components["schemas"]["BarRead"] | components["schemas"]["Arith-Input"] | components["schemas"]["Call-Input"] | components["schemas"]["Previous-Input"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "crossed";
            /** Right */
            right: components["schemas"]["Const"] | components["schemas"]["ParamRef"] | components["schemas"]["FactRead"] | components["schemas"]["BarRead"] | components["schemas"]["Arith-Input"] | components["schemas"]["Call-Input"] | components["schemas"]["Previous-Input"];
        };
        /**
         * Crossed
         * @description Two expressions crossing on this bar — the one piece of sugar in the vocabulary. A crossing expressed
         *     as four comparisons over two frames is four places for one of them to drift.
         */
        "Crossed-Output": {
            /**
             * Direction
             * @enum {string}
             */
            direction: "above" | "below";
            /** Left */
            left: components["schemas"]["Const"] | components["schemas"]["ParamRef"] | components["schemas"]["FactRead"] | components["schemas"]["BarRead"] | components["schemas"]["Arith-Output"] | components["schemas"]["Call-Output"] | components["schemas"]["Previous-Output"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "crossed";
            /** Right */
            right: components["schemas"]["Const"] | components["schemas"]["ParamRef"] | components["schemas"]["FactRead"] | components["schemas"]["BarRead"] | components["schemas"]["Arith-Output"] | components["schemas"]["Call-Output"] | components["schemas"]["Previous-Output"];
        };
        /**
         * DecisionDetailOut
         * @description One decision with the readings it stood on — enough to re-decide it without the
         *     archive, which is what makes a recorded decision evidence rather than an anecdote.
         */
        DecisionDetailOut: {
            /**
             * Action
             * @enum {string}
             */
            action: "trade" | "no_trade";
            /**
             * As Of
             * Format: date-time
             * @description the closing time of the bar decided on, never a wall clock
             */
            as_of: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Direction */
            direction: ("long" | "short") | null;
            /** Entry */
            entry: number | null;
            /**
             * Facts
             * @description the snapshot `evaluate` was handed
             */
            facts: {
                [key: string]: unknown;
            };
            /**
             * Features
             * @description what the strategy measured, named
             */
            features: {
                [key: string]: number;
            };
            /** Id */
            id: number;
            /**
             * Parameter Set Id
             * @description which version of the parameters decided this
             */
            parameter_set_id: number;
            /** Reason */
            reason: string | null;
            /**
             * Reason Kind
             * @description which layer refused: the strategy itself, a gap in the data, or a platform limit. A gap is answered by fetching history; the strategy's own no is answered by reading the strategy
             */
            reason_kind: ("strategy" | "coverage" | "limit") | null;
            /**
             * Rr
             * @description reward over risk, from the levels
             */
            rr: number | null;
            /** Score */
            score: number | null;
            /** Stop */
            stop: number | null;
            /** Strategy Id */
            strategy_id: string;
            /**
             * Strategy Revision
             * @description that revision's own number, so a reader needs no second call
             */
            strategy_revision: number | null;
            /**
             * Strategy Revision Id
             * @description which revision of the rule decided this; null for code
             */
            strategy_revision_id: number | null;
            /** Symbol */
            symbol: string;
            /** Target */
            target: number | null;
        };
        /** DecisionOut */
        DecisionOut: {
            /**
             * Action
             * @enum {string}
             */
            action: "trade" | "no_trade";
            /**
             * As Of
             * Format: date-time
             * @description the closing time of the bar decided on, never a wall clock
             */
            as_of: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Direction */
            direction: ("long" | "short") | null;
            /** Entry */
            entry: number | null;
            /**
             * Features
             * @description what the strategy measured, named
             */
            features: {
                [key: string]: number;
            };
            /** Id */
            id: number;
            /**
             * Parameter Set Id
             * @description which version of the parameters decided this
             */
            parameter_set_id: number;
            /** Reason */
            reason: string | null;
            /**
             * Reason Kind
             * @description which layer refused: the strategy itself, a gap in the data, or a platform limit. A gap is answered by fetching history; the strategy's own no is answered by reading the strategy
             */
            reason_kind: ("strategy" | "coverage" | "limit") | null;
            /**
             * Rr
             * @description reward over risk, from the levels
             */
            rr: number | null;
            /** Score */
            score: number | null;
            /** Stop */
            stop: number | null;
            /** Strategy Id */
            strategy_id: string;
            /**
             * Strategy Revision
             * @description that revision's own number, so a reader needs no second call
             */
            strategy_revision: number | null;
            /**
             * Strategy Revision Id
             * @description which revision of the rule decided this; null for code
             */
            strategy_revision_id: number | null;
            /** Symbol */
            symbol: string;
            /** Target */
            target: number | null;
        };
        /**
         * DefinitionIn
         * @description A new clicked strategy: its identity, its name, and the first version of its rule.
         */
        DefinitionIn: {
            definition: components["schemas"]["RuleDefinition-Input"];
            /**
             * Description
             * @default
             */
            description: string;
            /** Name */
            name: string;
            /**
             * Strategy Id
             * @description lowercase, from the same namespace the coded entries use — one that a coded entry already claims is refused
             */
            strategy_id: string;
        };
        /** DefinitionOut */
        DefinitionOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string;
            /** Id */
            id: number;
            /**
             * Latest Version
             * @description the newest revision; a running watch may still be pinned to an older one
             */
            latest_version: number;
            /** Name */
            name: string;
            /** Strategy Id */
            strategy_id: string;
        };
        /**
         * DefinitionPatch
         * @description The two things about a definition that are not the rule. Changed in place rather than minted as a
         *     revision: provenance that shifted because somebody fixed a typo is provenance nobody could trust.
         */
        DefinitionPatch: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Name */
            name: string;
        };
        /** FactOut */
        FactOut: {
            /** Bars */
            bars: number;
            /**
             * Indicator
             * @description the archive's catalogue id
             */
            indicator: string;
            /**
             * Key
             * @description what the strategy reads this back under
             */
            key: string;
            /**
             * Params
             * @description a string names one of this strategy's own parameters
             */
            params: {
                [key: string]: number | string;
            };
            /** Resolution */
            resolution: string;
        };
        /**
         * FactRead
         * @description One line of one declared fact, at this bar or a few bars back. `offset` counts backwards from the bar being
         *     decided on, so `0` is the reading the loop calls "now" and `1` is the other half of every crossing test.
         */
        FactRead: {
            /** Key */
            key: string;
            /** Line */
            line: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "fact";
            /**
             * Offset
             * @default 0
             */
            offset: number;
        };
        /**
         * Guard
         * @description A reason to refuse, in the order it should be asked: the cheapest and commonest refusal belongs first, since
         *     the usual answer of a strategy worth running is "no".
         */
        "Guard-Input": {
            /** Reason */
            reason: string;
            /** When */
            when: components["schemas"]["Compare-Input"] | components["schemas"]["Logic-Input"] | components["schemas"]["Crossed-Input"] | components["schemas"]["Settled-Input"];
        };
        /**
         * Guard
         * @description A reason to refuse, in the order it should be asked: the cheapest and commonest refusal belongs first, since
         *     the usual answer of a strategy worth running is "no".
         */
        "Guard-Output": {
            /** Reason */
            reason: string;
            /** When */
            when: components["schemas"]["Compare-Output"] | components["schemas"]["Logic-Output"] | components["schemas"]["Crossed-Output"] | components["schemas"]["Settled-Output"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail: components["schemas"]["ValidationError"][];
        };
        /** Logic */
        "Logic-Input": {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "logic";
            /**
             * Op
             * @enum {string}
             */
            op: "all" | "any" | "not";
            /** Operands */
            operands: (components["schemas"]["Compare-Input"] | components["schemas"]["Logic-Input"] | components["schemas"]["Crossed-Input"] | components["schemas"]["Settled-Input"])[];
        };
        /** Logic */
        "Logic-Output": {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "logic";
            /**
             * Op
             * @enum {string}
             */
            op: "all" | "any" | "not";
            /** Operands */
            operands: (components["schemas"]["Compare-Output"] | components["schemas"]["Logic-Output"] | components["schemas"]["Crossed-Output"] | components["schemas"]["Settled-Output"])[];
        };
        /** ParamOut */
        ParamOut: {
            /** Default */
            default: number;
            /** Max */
            max: number;
            /** Min */
            min: number;
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "int" | "float";
        };
        /** ParamRef */
        ParamRef: {
            /** Name */
            name: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "param";
        };
        /** ParameterSetIn */
        ParameterSetIn: {
            /**
             * Params
             * @description defaults are filled in for anything omitted
             */
            params?: {
                [key: string]: number;
            };
            /** Strategy Id */
            strategy_id: string;
        };
        /** ParameterSetOut */
        ParameterSetOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /**
             * Params
             * @description resolved — defaults filled in
             */
            params: {
                [key: string]: number;
            };
            /** Strategy Id */
            strategy_id: string;
            /**
             * Strategy Revision Id
             * @description the revision whose declaration these values were checked against; null for a coded entry, whose declaration is in the image
             */
            strategy_revision_id: number | null;
            /**
             * Version
             * @description append-only; a change of mind is the next version
             */
            version: number;
        };
        /**
         * Previous
         * @description The same expression, evaluated one bar earlier — a frame shift rather than an offset on every leaf inside it:
         *     `previous(fast − slow)` says what it means, while shifting each leaf by hand is three places to forget one.
         */
        "Previous-Input": {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "previous";
            /** Of */
            of: components["schemas"]["Const"] | components["schemas"]["ParamRef"] | components["schemas"]["FactRead"] | components["schemas"]["BarRead"] | components["schemas"]["Arith-Input"] | components["schemas"]["Call-Input"] | components["schemas"]["Previous-Input"];
        };
        /**
         * Previous
         * @description The same expression, evaluated one bar earlier — a frame shift rather than an offset on every leaf inside it:
         *     `previous(fast − slow)` says what it means, while shifting each leaf by hand is three places to forget one.
         */
        "Previous-Output": {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "previous";
            /** Of */
            of: components["schemas"]["Const"] | components["schemas"]["ParamRef"] | components["schemas"]["FactRead"] | components["schemas"]["BarRead"] | components["schemas"]["Arith-Output"] | components["schemas"]["Call-Output"] | components["schemas"]["Previous-Output"];
        };
        /**
         * RevisionIn
         * @description The next revision of an existing definition. The previous one stays as it was.
         */
        RevisionIn: {
            definition: components["schemas"]["RuleDefinition-Input"];
        };
        /** RevisionOut */
        RevisionOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            definition: components["schemas"]["RuleDefinition-Output"];
            /** Id */
            id: number;
            /** Strategy Id */
            strategy_id: string;
            /** Version */
            version: number;
        };
        /**
         * RuleDefinition
         * @description The whole of what a revision carries. `unsettled_reason` is declared rather than fixed by the
         *     platform: "it has not settled" means something different for an average than for a structure.
         */
        "RuleDefinition-Input": {
            /**
             * Candles
             * @default 300
             */
            candles: number;
            /** Facts */
            facts?: components["schemas"]["RuleFact"][];
            /** Features */
            features?: {
                [key: string]: components["schemas"]["Const"] | components["schemas"]["ParamRef"] | components["schemas"]["FactRead"] | components["schemas"]["BarRead"] | components["schemas"]["Arith-Input"] | components["schemas"]["Call-Input"] | components["schemas"]["Previous-Input"];
            };
            /** Guards */
            guards?: components["schemas"]["Guard-Input"][];
            /** No Setup Reason */
            no_setup_reason: string;
            /** Params */
            params?: components["schemas"]["RuleParam"][];
            /**
             * Resolution
             * @description the bars whose closes drive evaluation
             */
            resolution: string;
            /** Setups */
            setups: components["schemas"]["Setup-Input"][];
            /** Unsettled Reason */
            unsettled_reason: string;
        };
        /**
         * RuleDefinition
         * @description The whole of what a revision carries. `unsettled_reason` is declared rather than fixed by the
         *     platform: "it has not settled" means something different for an average than for a structure.
         */
        "RuleDefinition-Output": {
            /**
             * Candles
             * @default 300
             */
            candles: number;
            /** Facts */
            facts: components["schemas"]["RuleFact"][];
            /** Features */
            features: {
                [key: string]: components["schemas"]["Const"] | components["schemas"]["ParamRef"] | components["schemas"]["FactRead"] | components["schemas"]["BarRead"] | components["schemas"]["Arith-Output"] | components["schemas"]["Call-Output"] | components["schemas"]["Previous-Output"];
            };
            /** Guards */
            guards: components["schemas"]["Guard-Output"][];
            /** No Setup Reason */
            no_setup_reason: string;
            /** Params */
            params: components["schemas"]["RuleParam"][];
            /**
             * Resolution
             * @description the bars whose closes drive evaluation
             */
            resolution: string;
            /** Setups */
            setups: components["schemas"]["Setup-Output"][];
            /** Unsettled Reason */
            unsettled_reason: string;
        };
        /**
         * RuleFact
         * @description One reading the platform fetches on this rule's behalf, named the archive's way.
         */
        RuleFact: {
            /**
             * Bars
             * @default 300
             */
            bars: number;
            /**
             * Indicator
             * @description the archive's catalogue id
             */
            indicator: string;
            /**
             * Key
             * @description what the rule reads this back under
             */
            key: string;
            /**
             * Params
             * @description a string names one of this rule's own parameters
             */
            params?: {
                [key: string]: number | string;
            };
            /** Resolution */
            resolution: string;
        };
        /**
         * RuleParam
         * @description One tunable number of a clicked strategy, with the range outside which it is not a
         *     value at all. The same shape `spec.Param` has, on the wire and in the row.
         */
        RuleParam: {
            /** Default */
            default: number;
            /** Max */
            max: number;
            /** Min */
            min: number;
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "int" | "float";
        };
        /**
         * Settled
         * @description Whether every one of these readings exists at all. Never undetermined itself: it is how a rule asks
         *     about that state instead of being carried along by it, ahead of the guards.
         */
        "Settled-Input": {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "settled";
            /** Of */
            of: (components["schemas"]["Const"] | components["schemas"]["ParamRef"] | components["schemas"]["FactRead"] | components["schemas"]["BarRead"] | components["schemas"]["Arith-Input"] | components["schemas"]["Call-Input"] | components["schemas"]["Previous-Input"])[];
        };
        /**
         * Settled
         * @description Whether every one of these readings exists at all. Never undetermined itself: it is how a rule asks
         *     about that state instead of being carried along by it, ahead of the guards.
         */
        "Settled-Output": {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "settled";
            /** Of */
            of: (components["schemas"]["Const"] | components["schemas"]["ParamRef"] | components["schemas"]["FactRead"] | components["schemas"]["BarRead"] | components["schemas"]["Arith-Output"] | components["schemas"]["Call-Output"] | components["schemas"]["Previous-Output"])[];
        };
        /**
         * Setup
         * @description One way this rule says yes — a direction, its levels, and what it calls itself.
         */
        "Setup-Input": {
            /**
             * Direction
             * @enum {string}
             */
            direction: "long" | "short";
            /** Entry */
            entry: components["schemas"]["Const"] | components["schemas"]["ParamRef"] | components["schemas"]["FactRead"] | components["schemas"]["BarRead"] | components["schemas"]["Arith-Input"] | components["schemas"]["Call-Input"] | components["schemas"]["Previous-Input"];
            /** Reason */
            reason: string;
            /** Score */
            score?: (components["schemas"]["Const"] | components["schemas"]["ParamRef"] | components["schemas"]["FactRead"] | components["schemas"]["BarRead"] | components["schemas"]["Arith-Input"] | components["schemas"]["Call-Input"] | components["schemas"]["Previous-Input"]) | null;
            /** Stop */
            stop: components["schemas"]["Const"] | components["schemas"]["ParamRef"] | components["schemas"]["FactRead"] | components["schemas"]["BarRead"] | components["schemas"]["Arith-Input"] | components["schemas"]["Call-Input"] | components["schemas"]["Previous-Input"];
            /** Target */
            target: components["schemas"]["Const"] | components["schemas"]["ParamRef"] | components["schemas"]["FactRead"] | components["schemas"]["BarRead"] | components["schemas"]["Arith-Input"] | components["schemas"]["Call-Input"] | components["schemas"]["Previous-Input"];
            /** When */
            when: components["schemas"]["Compare-Input"] | components["schemas"]["Logic-Input"] | components["schemas"]["Crossed-Input"] | components["schemas"]["Settled-Input"];
        };
        /**
         * Setup
         * @description One way this rule says yes — a direction, its levels, and what it calls itself.
         */
        "Setup-Output": {
            /**
             * Direction
             * @enum {string}
             */
            direction: "long" | "short";
            /** Entry */
            entry: components["schemas"]["Const"] | components["schemas"]["ParamRef"] | components["schemas"]["FactRead"] | components["schemas"]["BarRead"] | components["schemas"]["Arith-Output"] | components["schemas"]["Call-Output"] | components["schemas"]["Previous-Output"];
            /** Reason */
            reason: string;
            /** Score */
            score: (components["schemas"]["Const"] | components["schemas"]["ParamRef"] | components["schemas"]["FactRead"] | components["schemas"]["BarRead"] | components["schemas"]["Arith-Output"] | components["schemas"]["Call-Output"] | components["schemas"]["Previous-Output"]) | null;
            /** Stop */
            stop: components["schemas"]["Const"] | components["schemas"]["ParamRef"] | components["schemas"]["FactRead"] | components["schemas"]["BarRead"] | components["schemas"]["Arith-Output"] | components["schemas"]["Call-Output"] | components["schemas"]["Previous-Output"];
            /** Target */
            target: components["schemas"]["Const"] | components["schemas"]["ParamRef"] | components["schemas"]["FactRead"] | components["schemas"]["BarRead"] | components["schemas"]["Arith-Output"] | components["schemas"]["Call-Output"] | components["schemas"]["Previous-Output"];
            /** When */
            when: components["schemas"]["Compare-Output"] | components["schemas"]["Logic-Output"] | components["schemas"]["Crossed-Output"] | components["schemas"]["Settled-Output"];
        };
        /**
         * StrategyOut
         * @description One catalogue entry as it can be read from outside — everything but its function.
         */
        StrategyOut: {
            /** Candles */
            candles: number;
            /** Description */
            description: string;
            /** Facts */
            facts: components["schemas"]["FactOut"][];
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Params */
            params: components["schemas"]["ParamOut"][];
            /**
             * Resolution
             * @description the bars whose closes drive evaluation
             */
            resolution: string;
            /**
             * Revision
             * @description the revision this was built from; null for a coded entry
             */
            revision: number | null;
            /**
             * Source
             * @description whether this entry is code in the deployed image or a stored revision — a coded entry has no revisions and cannot be edited
             * @default code
             * @enum {string}
             */
            source: "code" | "revision";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx: Record<string, never>;
            /** Input */
            input: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WatchIn */
        WatchIn: {
            /**
             * Parameter Set Id
             * @description omit to have a set written from this strategy's defaults
             */
            parameter_set_id?: number | null;
            /**
             * Revision
             * @description which revision to pin this watch to; omit for the newest at this moment. A watch never follows later revisions — moving it is a second call
             */
            revision?: number | null;
            /** Strategy Id */
            strategy_id: string;
            /** Symbol */
            symbol: string;
        };
        /** WatchOut */
        WatchOut: {
            /** Active */
            active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Parameter Set Id */
            parameter_set_id: number;
            /** Strategy Id */
            strategy_id: string;
            /**
             * Strategy Revision Id
             * @description the revision this watch computes — pinned, never followed. Null means the strategy is code in the image
             */
            strategy_revision_id: number | null;
            /** Symbol */
            symbol: string;
        };
        /** WatchPatch */
        WatchPatch: {
            /** Active */
            active: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_backtests_backtests_get: {
        parameters: {
            query?: {
                strategy_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_backtest_backtests__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_decisions_decisions_get: {
        parameters: {
            query?: {
                strategy_id?: string | null;
                symbol?: string | null;
                action?: ("trade" | "no_trade") | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_decision_decisions__decision_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                decision_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_definitions_definitions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefinitionOut"][];
                };
            };
        };
    };
    add_definition_definitions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DefinitionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_definition_definitions__strategy_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefinitionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_definition_definitions__strategy_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DefinitionPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefinitionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_revisions_definitions__strategy_id__revisions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_revision_definitions__strategy_id__revisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_revision_definitions__strategy_id__revisions__version__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_parameter_sets_parameter_sets_get: {
        parameters: {
            query?: {
                strategy_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParameterSetOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_parameter_set_parameter_sets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParameterSetIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParameterSetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ping_ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_strategies_strategies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyOut"][];
                };
            };
        };
    };
    read_strategy_strategies__strategy_id__get: {
        parameters: {
            query?: {
                revision?: number | null;
            };
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_watches_watches_get: {
        parameters: {
            query?: {
                active_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_watch_watches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_watch_active_watches__watch_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watch_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
