/**
 * GENERATED — do not edit. Rewrite it with `pnpm contract:generate`.
 *
 * The source is market-data's own OpenAPI document, printed straight from its Pydantic
 * models by `python -m market_data.openapi`. Everything the terminal reads off that
 * module's wire — including the subscription's Snapshot and CandleChange, which have no
 * HTTP path — is described here, so `tsc` is what notices a contract change rather than
 * an operator noticing a blank cell.
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/asset-classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Asset Classes */
        get: operations["asset_classes_asset_classes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candles/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Candles for one pair over a time range
         * @description Answers with the series and, separately, the stretches of the requested range the archive never verified. Those are not the same as periods with no candle: a closed market has no candle either, and only one of the two is missing data.
         *
         *     Resolutions between MINUTE_5 and HOUR_4 are computed from the minute series rather than collected separately — the provider serves 1000 candles per request at ten requests a second, so fetching each one costs its own traffic for data the finest already implies. MINUTE, DAY and WEEK come from the provider: a daily boundary follows the venue's session, not the clock.
         */
        get: operations["candles_candles__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candles/{symbol}/forming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The period being built right now, for one pair
         * @description The current price, as the candle the archive is building this instant — the same one a subscription's snapshot carries, without the handshake a subscription costs. Nothing here is stored: a forming candle changes with every quote and understates its own range until the period closes.
         *
         *     Omit `resolution` and the archive answers from the finest one that actually has quotes arriving, which is not the same as the finest one tracked — a stalled minute feed on a pair also tracked hourly still has a price. Name one and it is honoured.
         *
         *     An answer with no candle says which of three reasons it is: nobody collects this symbol, the market is shut, or it is open and nothing is arriving anyway. The last one is a collection failure, and it is the reason this is not simply a nullable candle.
         */
        get: operations["forming_candle_candles__symbol__forming_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coverage/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What the archive has verified for one pair */
        get: operations["coverage_coverage__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deletions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recorded deletions, newest first */
        get: operations["deletions_deletions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Whether the archive can answer at all, which means whether its database can.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/indicators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every indicator this module can compute, and how to draw it
         * @description A consumer builds its whole picker from this — parameters, defaults, output shape, render hint — and never needs to know an indicator by name beforehand.
         */
        get: operations["catalogue_indicators_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/indicators/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compute one or more indicators over a range, on one shared time axis
         * @description Reads further back than `from` on its own, by however much each requested indicator's warmup needs, and says in `warmup_from`/`settled` whether the archive actually held enough history for the answer to be trusted.
         */
        post: operations["compute_indicators__symbol__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalogue */
        get: operations["catalogue_instruments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_instruments_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Collection jobs, one row per pair they touched */
        get: operations["jobs_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Price a collection job without creating it
         * @description Runs the exact planning a job creation would, without writing anything: no pair is tracked, no job exists afterwards. A symbol the gateway does not know comes back marked `unknown` rather than failing the whole estimate.
         */
        post: operations["estimate_pairs_jobs_estimate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One job, whole — every pair and every chunk it covers */
        get: operations["job_jobs__job_id__get"];
        put?: never;
        post?: never;
        /**
         * Remove a job from the collection history
         * @description Removes the job and every chunk it was planned into. **No candle is deleted**: the data this job collected, and the coverage that follows from it, stay in the archive — deleting a pair's data is `DELETE /pairs/{symbol}` and is a different operation. Refused with 409 while any chunk is still pending or running, since its result would be written against a job that no longer exists.
         */
        delete: operations["remove_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry a job's failed or interrupted chunks
         * @description Resets only chunks left `failed` or `interrupted`, as a new attempt of the same job — never a new job, and never a chunk already `done`. Refused with 409 when there is nothing to retry.
         */
        post: operations["retry_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pairs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Which pairs are collected, and whether collection is happening */
        get: operations["pairs_pairs_get"];
        put?: never;
        /**
         * Start collecting one or more pairs
         * @description Each pair is validated against the gateway independently, so one refusal — an unknown symbol, the tracked-pairs ceiling — never withholds the pairs that were fine. Accepting at least one pair that needed history behind it starts a collection job and returns its id; a request whose pairs were all already fully covered accepts them with no job. The original single-pair shape (`symbol`, `resolution`) still works and still means the configured default depth.
         */
        post: operations["track_pairs_pairs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pairs/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Stop collecting a pair and delete its data
         * @description Stops collection, releases the provider connection, and removes every candle and coverage range this pair holds — irreversibly. A symbol whose minute series is deleted also loses the rollups computed from it. 404 for a pair not currently tracked, which deletes nothing.
         */
        delete: operations["delete_pair_pairs__symbol__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ping
         * @description Proves only that the process is up and serving — nothing about its dependencies.
         *
         *     Reads nothing: `/health` above already answers whether the database is reachable, and
         *     an external prober checking that would read a healthy process as dead the moment a
         *     query ran slow. This is what Easy Auth's `excluded_paths` (infra/app-service.tf) can
         *     exempt without exposing anything — the response never varies with the archive's state.
         */
        get: operations["ping_ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stream-tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * A one-time ticket for opening the candle stream
         * @description A browser cannot put a header on a WebSocket handshake, so a consumer running in one proves who it is here — where headers work — and spends the answer there. The ticket is good for one handshake and for a few seconds; asking again is the only way to get another, including after a dropped connection.
         */
        post: operations["issue_stream_ticket_stream_tickets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Candle
         * @description One candle, identified by symbol, resolution and the start of its period.
         *
         *     Edges are optional because the gateway's are: the provider occasionally omits one,
         *     and a candle with a missing edge is still better evidence than no candle at all.
         */
        Candle: {
            /**
             * Close
             * @default null
             */
            close: number | null;
            /**
             * Forming
             * @default false
             */
            forming: boolean;
            /**
             * High
             * @default null
             */
            high: number | null;
            /**
             * Low
             * @default null
             */
            low: number | null;
            /**
             * Open
             * @default null
             */
            open: number | null;
            /**
             * Period Start
             * Format: date-time
             */
            period_start: string;
            /** @default bid */
            price_side: components["schemas"]["PriceSide"];
            resolution: components["schemas"]["Resolution"];
            source: components["schemas"]["CandleSource"];
            /** Symbol */
            symbol: string;
            /**
             * Volume
             * @default null
             */
            volume: number | null;
        };
        /**
         * CandleChange
         * @description One candle, closed or still forming, said explicitly.
         *
         *     One message kind for both, marked rather than split, because a consumer upserts by
         *     period start and two message types would only make it reconcile them itself. The mark
         *     is what stops a chart treating a period still moving as settled.
         */
        CandleChange: {
            candle: components["schemas"]["Candle"];
            /**
             * Kind
             * @default candle
             * @constant
             */
            kind: "candle";
            resolution: components["schemas"]["Resolution"];
            /** Symbol */
            symbol: string;
        };
        /**
         * CandleOut
         * @description One settled candle. No `forming`: everything in a range read has closed.
         */
        CandleOut: {
            /** Close */
            close: number | null;
            /** High */
            high: number | null;
            /** Low */
            low: number | null;
            /** Open */
            open: number | null;
            /**
             * Time
             * Format: date-time
             * @description the start of the candle's period, UTC
             */
            time: string;
            /** Volume */
            volume: number | null;
        };
        /**
         * CandleSource
         * @description Which way a candle reached the archive.
         *
         *     Kept because the two are not equally trustworthy: a stream that was disconnected
         *     misses quotes and understates a candle's range, while a history read sees the period
         *     whole. Which one wins is decided by the archive, and it cannot decide without this.
         * @enum {string}
         */
        CandleSource: "history" | "stream";
        /**
         * CandlesOut
         * @description A range read, and everything needed to know what it is not saying.
         *
         *     `uncovered` is the part that matters and the part a plain list of candles cannot
         *     express. An empty series over a weekend and an empty series because ingest was down
         *     are the same list; only one of them is the whole story.
         */
        CandlesOut: {
            /** Candles */
            candles: components["schemas"]["CandleOut"][];
            /**
             * Derived
             * @description true when the series was computed from the minute series rather than collected at this resolution
             */
            derived: boolean;
            /** @description which side of the spread these are built from; the archive holds bid */
            price_side: components["schemas"]["PriceSide"];
            resolution: components["schemas"]["Resolution"];
            /** Symbol */
            symbol: string;
            /**
             * Uncovered
             * @description stretches of the requested range the archive never verified
             */
            uncovered: components["schemas"]["Uncovered"][];
        };
        /** ChunkOut */
        ChunkOut: {
            /** Attempt */
            attempt: number;
            /** Candles Written */
            candles_written: number;
            /**
             * Chunk End
             * Format: date-time
             */
            chunk_end: string;
            /**
             * Chunk Start
             * Format: date-time
             */
            chunk_start: string;
            /** Failure */
            failure: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: number;
            /** Requests */
            requests: number;
            resolution: components["schemas"]["Resolution"];
            /** Started At */
            started_at: string | null;
            state: components["schemas"]["ChunkState"];
            /** Symbol */
            symbol: string;
        };
        /**
         * ChunkState
         * @description One chunk's life. `interrupted` is reached only from `pending` or `running`, and
         *     only by this module's own startup — no runner survives a restart, so anything not
         *     yet settled at that moment was orphaned, not merely delayed.
         * @enum {string}
         */
        ChunkState: "pending" | "running" | "done" | "failed" | "skipped" | "interrupted";
        /**
         * CollectionState
         * @description Whether data is actually arriving, as far as the archive can tell.
         *
         *     Being on the list proves nothing. A subscription can die without a sound, and the
         *     only visible symptom is a series that stops growing while the market is open.
         * @enum {string}
         */
        CollectionState: "never_collected" | "collecting" | "stalled" | "market_closed" | "unknown";
        /** CoverageOut */
        CoverageOut: {
            /**
             * From
             * Format: date-time
             */
            from: string;
            /**
             * History Ended
             * @description true when the provider has nothing older than `from`
             */
            history_ended: boolean;
            /**
             * To
             * Format: date-time
             */
            to: string;
        };
        /** EstimateRequest */
        EstimateRequest: {
            /**
             * Collect From
             * Format: date-time
             * @description moment history should reach back to
             */
            collect_from: string;
            /** Pairs */
            pairs: components["schemas"]["PairRequest"][];
        };
        /**
         * FormingCandleOut
         * @description The period being built right now, read rather than subscribed to.
         *
         *     The candle is the same one a subscription's snapshot would carry this instant, and it
         *     is not stored anywhere: it changes with every quote and understates its own range until
         *     the period closes. A consumer treating `high`/`low` here as the period's range will be
         *     wrong before the period ends — which is why `state` says `forming` in words rather than
         *     leaving it to be inferred from a field being present.
         */
        FormingCandleOut: {
            /** @description null unless `state` is `forming` */
            candle: components["schemas"]["CandleOut"] | null;
            /**
             * Market Open
             * @description null when the gateway could not be asked — not the same as closed
             */
            market_open: boolean | null;
            /** @description which side of the spread this is built from; the archive holds bid */
            price_side: components["schemas"]["PriceSide"];
            /** @description which resolution this candle came from; null when there is none to answer with. May differ from the one asked for, because a caller that names none is answered from the finest resolution that actually has quotes arriving */
            resolution: components["schemas"]["Resolution"] | null;
            state: components["schemas"]["FormingState"];
            /** Symbol */
            symbol: string;
        };
        /**
         * FormingState
         * @description Why a read of the current period does or does not carry a candle.
         *
         *     Four answers rather than a candle and a null, because the three empty ones send an
         *     operator somewhere different: add the pair, come back on Monday, or go and look at why
         *     collection stopped. Only the last is anybody's problem right now, and without a name it
         *     reads exactly like the other two.
         * @enum {string}
         */
        FormingState: "forming" | "not_tracked" | "market_closed" | "no_quotes";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail: components["schemas"]["ValidationError"][];
        };
        /**
         * IndicatorCatalogueEntryOut
         * @description One row of `GET /indicators` — everything a consumer needs to offer this
         *     indicator and draw it, without knowing anything about it beforehand
         *     (`market-data-indicators` spec, "Katalog wystarcza do zbudowania wybieraka").
         */
        IndicatorCatalogueEntryOut: {
            /**
             * Aliases
             * @description names an indicator is also known by; never the vocabulary of one trading school baked into `id` itself
             */
            aliases: string[];
            /** Group */
            group: string;
            /** Id */
            id: string;
            /** Lines */
            lines: components["schemas"]["IndicatorLineSpecOut"][];
            /** Name */
            name: string;
            /**
             * Output
             * @enum {string}
             */
            output: "lines" | "markers" | "zones" | "levels";
            /** Params */
            params: components["schemas"]["IndicatorParamOut"][];
            render: components["schemas"]["IndicatorRenderOut"];
            /**
             * Warmup Kind
             * @enum {string}
             */
            warmup_kind: "fixed" | "decay";
        };
        /** IndicatorLevelOut */
        IndicatorLevelOut: {
            /**
             * Count
             * @description how many extrema support this level; null for a level that carries no weight, e.g. a pivot or a previous-period edge
             */
            count: number | null;
            /**
             * From
             * Format: date-time
             */
            from: string;
            /** Label */
            label: string | null;
            /** Price */
            price: number;
        };
        /** IndicatorLineSpecOut */
        IndicatorLineSpecOut: {
            /** Key */
            key: string;
            /**
             * Label
             * @description e.g. 'EMA {period}' — a template, not a rendered string
             */
            label: string;
            /**
             * Style
             * @description Overrides the entry's own render.style for this one line — MACD's histogram line inside an otherwise line-style entry, and the only reason this field exists. Null means: use render.style.
             */
            style: ("line" | "dots" | "histogram") | null;
        };
        /** IndicatorMarkerOut */
        IndicatorMarkerOut: {
            /** Label */
            label: string;
            /** Price */
            price: number | null;
            /**
             * Time
             * Format: date-time
             */
            time: string;
        };
        /** IndicatorParamOut */
        IndicatorParamOut: {
            /** Default */
            default: number;
            /** Max */
            max: number;
            /** Min */
            min: number;
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "int" | "float";
        };
        /** IndicatorRenderOut */
        IndicatorRenderOut: {
            /**
             * Autoscale
             * @description whether this line may widen the price axis it shares — off for an indicator whose own values are not comparable to price
             * @default true
             */
            autoscale: boolean;
            /**
             * Levels
             * @description reference lines to draw, e.g. 30/70 for RSI
             */
            levels: number[];
            /**
             * Pane
             * @enum {string}
             */
            pane: "price" | "own";
            /** Range */
            range: [
                number,
                number
            ] | null;
            /**
             * Scale
             * @default price
             * @enum {string}
             */
            scale: "price" | "own" | "fixed";
            /**
             * Style
             * @enum {string}
             */
            style: "line" | "dots" | "histogram";
        };
        /**
         * IndicatorResultOut
         * @description One requested indicator's answer. Exactly one of `lines`, `markers`, `zones`,
         *     `levels` is set — the one its catalogue entry's `output` names — or none of them
         *     and `error` instead (`market-data-indicators` spec, "Wynik ma jeden z czterech
         *     kształtów").
         */
        IndicatorResultOut: {
            /**
             * Error
             * @description why this one indicator could not be computed, when the reason is something the archive does not hold — the series it needs at a resolution nobody collects. Set instead of a shape, never beside one: an empty `zones` means the range held none, which is not the same claim. A request the module refuses outright (unknown indicator, parameter out of range, reversed range, over the ceiling) is a 422 carrying Problem, not a result carrying this
             */
            error: string | null;
            /** Id */
            id: string;
            /** Levels */
            levels: components["schemas"]["IndicatorLevelOut"][] | null;
            /** Lines */
            lines: {
                [key: string]: (number | null)[];
            } | null;
            /** Markers */
            markers: components["schemas"]["IndicatorMarkerOut"][] | null;
            /**
             * Params
             * @description resolved params — defaults filled in
             */
            params: {
                [key: string]: number;
            };
            /**
             * Settled
             * @description false when the archive did not hold enough history before the requested range for this value to be trusted yet. Says nothing about `error`: an unsettled value is still a value, computed from a series that was shorter than it wanted
             */
            settled: boolean;
            /**
             * Warmup Bars
             * @description how many bars before the requested range were read for warmup; null for one that carries an error instead of an answer
             */
            warmup_bars: number | null;
            /** Zones */
            zones: components["schemas"]["IndicatorZoneOut"][] | null;
        };
        /** IndicatorSpecIn */
        IndicatorSpecIn: {
            /**
             * Id
             * @example ema
             */
            id: string;
            /** Params */
            params?: {
                [key: string]: number;
            };
        };
        /** IndicatorZoneOut */
        IndicatorZoneOut: {
            /** Bottom */
            bottom: number;
            /** Direction */
            direction: ("bullish" | "bearish") | null;
            /** Filled At */
            filled_at: string | null;
            /**
             * From
             * Format: date-time
             */
            from: string;
            /**
             * To
             * @description null while the zone has not closed within the read range
             */
            to: string | null;
            /** Top */
            top: number;
            /** Touched At */
            touched_at: string | null;
        };
        /** IndicatorsCatalogueOut */
        IndicatorsCatalogueOut: {
            /** Algorithm Version */
            algorithm_version: number;
            /** Indicators */
            indicators: components["schemas"]["IndicatorCatalogueEntryOut"][];
        };
        /**
         * IndicatorsOut
         * @description `POST /indicators/{symbol}` — one or more indicators, on one shared time axis.
         */
        IndicatorsOut: {
            /** Algorithm Version */
            algorithm_version: number;
            /**
             * Derived
             * @description true when computed from a resolution derived from the minute series
             */
            derived: boolean;
            /** @description which side of the spread these were computed from; the archive holds bid */
            price_side: components["schemas"]["PriceSide"];
            resolution: components["schemas"]["Resolution"];
            /** Results */
            results: components["schemas"]["IndicatorResultOut"][];
            /** Symbol */
            symbol: string;
            /**
             * Times
             * @description shared by every result below
             */
            times: string[];
            /**
             * Uncovered
             * @description stretches of the requested range the archive never verified
             */
            uncovered: components["schemas"]["Uncovered"][];
            /**
             * Warmup From
             * @description oldest period actually read to satisfy warmup; null when no requested indicator needed any
             */
            warmup_from: string | null;
        };
        /** IndicatorsRequest */
        IndicatorsRequest: {
            /**
             * From
             * Format: date-time
             * @description inclusive, UTC
             */
            from: string;
            /**
             * @default MINUTE
             * @example MINUTE
             */
            resolution: components["schemas"]["Resolution"];
            /** Specs */
            specs: components["schemas"]["IndicatorSpecIn"][];
            /**
             * To
             * Format: date-time
             * @description exclusive, UTC
             */
            to: string;
        };
        /** JobEstimateOut */
        JobEstimateOut: {
            /** Pairs */
            pairs: components["schemas"]["PairEstimateOut"][];
            /** Total Estimated Bytes */
            total_estimated_bytes: number;
            /** Total Estimated Candles */
            total_estimated_candles: number;
        };
        /**
         * JobOut
         * @description A whole job — every pair it touched. What `GET /jobs/{id}` and
         *     `POST /jobs/{id}/retry` answer with; `GET /jobs` answers with `JobPairViewOut`.
         */
        JobOut: {
            /** Attempt */
            attempt: number;
            /** Candles Written */
            candles_written: number;
            /** Chunks */
            chunks: components["schemas"]["ChunkOut"][];
            /** Chunks Done */
            chunks_done: number;
            /** Chunks Total */
            chunks_total: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /**
             * Last Activity At
             * Format: date-time
             * @description When something last happened in this job — a chunk starting counts, not only one settling. Falls back to the job's creation while no chunk has been claimed yet.
             */
            last_activity_at: string;
            /**
             * Requested From
             * Format: date-time
             */
            requested_from: string;
            running_pair: components["schemas"]["RunningPair"] | null;
            status: components["schemas"]["JobStatus"];
        };
        /**
         * JobPairViewOut
         * @description One job, narrowed to one pair — what `GET /jobs` answers with.
         */
        JobPairViewOut: {
            /** Attempt */
            attempt: number;
            /** Candles Written */
            candles_written: number;
            /** Chunks */
            chunks: components["schemas"]["ChunkOut"][];
            /** Chunks Done */
            chunks_done: number;
            /** Chunks Total */
            chunks_total: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Job Id */
            job_id: number;
            /**
             * Last Activity At
             * Format: date-time
             * @description When something last happened for this pair — a chunk starting counts, not only one settling, so a long chunk reads as work rather than a stall. Falls back to the job's creation while no chunk has been claimed yet. This is the only field that tells a running job apart from a stuck one: progress and candle counts look identical for both.
             */
            last_activity_at: string;
            /**
             * Requested From
             * Format: date-time
             */
            requested_from: string;
            resolution: components["schemas"]["Resolution"];
            status: components["schemas"]["JobStatus"];
            /** Symbol */
            symbol: string;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "running" | "succeeded" | "partial" | "failed" | "interrupted";
        /** PairCoverageOut */
        PairCoverageOut: {
            /**
             * Earliest Reachable
             * @description the oldest moment worth asking the provider about; null means the end of its history has not been reached, not that there is no limit
             */
            earliest_reachable: string | null;
            /** Ranges */
            ranges: components["schemas"]["CoverageOut"][];
            resolution: components["schemas"]["Resolution"];
            /** Symbol */
            symbol: string;
        };
        /**
         * PairDeletionOut
         * @description What `DELETE /pairs/{symbol}` and `GET /deletions` answer with — the trace of one
         *     skasowanie, kept after the data itself is gone.
         */
        PairDeletionOut: {
            /**
             * Candles Removed
             * @description how many candles were removed; 0 is a valid count
             */
            candles_removed: number;
            /**
             * Deleted At
             * Format: date-time
             */
            deleted_at: string;
            /**
             * Removed From
             * @description the oldest removed candle's period; null together with `removed_to` when the pair had never collected anything
             */
            removed_from: string | null;
            /**
             * Removed To
             * @description the newest removed candle's period; null with `removed_from`
             */
            removed_to: string | null;
            resolution: components["schemas"]["Resolution"];
            /** Symbol */
            symbol: string;
        };
        /** PairEstimateOut */
        PairEstimateOut: {
            /**
             * Clipped
             * @description true when `effective_from` differs from `collect_from`
             * @default false
             */
            clipped: boolean;
            /**
             * Effective From
             * @description what `collect_from` was actually clipped to; null when the symbol is unknown to the gateway
             */
            effective_from: string | null;
            /**
             * Estimated Bytes
             * @default 0
             */
            estimated_bytes: number;
            /**
             * Estimated Candles
             * @default 0
             */
            estimated_candles: number;
            resolution: components["schemas"]["Resolution"];
            /** Symbol */
            symbol: string;
            /**
             * Unknown
             * @description true when the gateway does not know this symbol
             * @default false
             */
            unknown: boolean;
        };
        /** PairRequest */
        PairRequest: {
            /**
             * @default MINUTE
             * @example MINUTE
             */
            resolution: components["schemas"]["Resolution"];
            /**
             * Symbol
             * @example US100
             */
            symbol: string;
        };
        /**
         * PriceSide
         * @description Which side of the spread a candle is built from.
         *
         *     Everything stored today is `BID`, the side the gateway builds both its history and
         *     its stream from. The value is written next to the data anyway, so that adding the
         *     other side one day is a schema change with a visible cost rather than two series
         *     quietly averaged into one.
         * @enum {string}
         */
        PriceSide: "bid" | "ask";
        /**
         * Problem
         * @description A refusal that names itself.
         *
         *     Never a database error and never a credential — a raw `asyncpg` message tells a
         *     consumer nothing it can act on while telling anyone reading the logs more about the
         *     schema than they need, and the caller's own token or stream ticket is never
         *     something a refusal has any reason to quote back.
         */
        Problem: {
            /** Detail */
            detail: string;
        };
        /**
         * Resolution
         * @description Candle time frame — the gateway's vocabulary, spelled its way.
         * @enum {string}
         */
        Resolution: "MINUTE" | "MINUTE_5" | "MINUTE_15" | "MINUTE_30" | "HOUR" | "HOUR_4" | "DAY" | "WEEK";
        /** RunningPair */
        RunningPair: {
            resolution: components["schemas"]["Resolution"];
            /** Symbol */
            symbol: string;
        };
        /**
         * Snapshot
         * @description The first message on every subscription, and the only one that looks backwards.
         *
         *     Carries the settled series and, separately, whatever period is currently being built.
         *     They are separate because they mean different things: one will never change again, the
         *     other changes with every quote.
         */
        Snapshot: {
            /** Candles */
            candles: components["schemas"]["Candle"][];
            /** @default null */
            forming: components["schemas"]["Candle"] | null;
            /**
             * Kind
             * @default snapshot
             * @constant
             */
            kind: "snapshot";
            resolution: components["schemas"]["Resolution"];
            /** Symbol */
            symbol: string;
        };
        /**
         * StreamTicketOut
         * @description Permission to open the stream once, and how long it stays good for.
         *
         *     The lifetime is answered rather than assumed so a consumer can tell a ticket it sat
         *     on too long from one the archive never issued — the handshake itself cannot say,
         *     since it refuses both the same way on purpose.
         */
        StreamTicketOut: {
            /**
             * Expires In Seconds
             * @description How long from now the ticket stays valid if it goes unused.
             */
            expires_in_seconds: number;
            /**
             * Ticket
             * @description Spend it on the next handshake. It works exactly once.
             */
            ticket: string;
        };
        /**
         * TrackPairRequest
         * @description Body for `POST /pairs`.
         *
         *     Two shapes, never mixed: the original single-pair one (`symbol`, `resolution`,
         *     still meaning exactly what it always did — no `collect_from` is the default depth)
         *     and a multi-pair one (`pairs`, `collect_from`) for adding several pairs as one
         *     decision. A consumer that has never heard of `pairs` keeps working unchanged.
         */
        TrackPairRequest: {
            /**
             * Collect From
             * @description moment history should reach back to; omitted means the configured default depth, exactly as before this field existed
             */
            collect_from?: string | null;
            /**
             * Pairs
             * @description multiple pairs added as one decision; excludes `symbol`
             */
            pairs?: components["schemas"]["PairRequest"][] | null;
            /**
             * @default MINUTE
             * @example MINUTE
             */
            resolution: components["schemas"]["Resolution"];
            /**
             * Symbol
             * @example US100
             */
            symbol?: string | null;
        };
        /** TrackPairsResult */
        TrackPairsResult: {
            /**
             * Job Id
             * @description the backfill job covering the accepted pairs, or null when nothing needed fetching
             */
            job_id: number | null;
            /** Results */
            results: components["schemas"]["TrackedPairResult"][];
        };
        /** TrackedPairOut */
        TrackedPairOut: {
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
            /**
             * Candle Count
             * @description how many candles are collected for this pair
             */
            candle_count: number;
            /**
             * Collect From
             * Format: date-time
             * @description the moment history for this pair is meant to reach back to
             */
            collect_from: string;
            /** @description whether data is actually arriving, as far as the archive can tell */
            collection: components["schemas"]["CollectionState"];
            /**
             * Earliest Candle
             * @description the oldest period collected — how far back the data actually reaches, which is not `collect_from` (where it was asked to reach) — or null if none yet
             */
            earliest_candle: string | null;
            /**
             * Estimated Bytes
             * @description a rough estimate of how much storage those candles take, derived from `candle_count` the same way a job's price is
             */
            estimated_bytes: number;
            /**
             * Latest Candle
             * @description the newest period collected, or null if none yet
             */
            latest_candle: string | null;
            resolution: components["schemas"]["Resolution"];
            /** Symbol */
            symbol: string;
        };
        /**
         * TrackedPairResult
         * @description One pair's outcome from `POST /pairs` — never a bare list of pairs, because a
         *     refusal for one must not be indistinguishable from silence about it.
         */
        TrackedPairResult: {
            /** @description present when this pair was accepted */
            pair: components["schemas"]["TrackedPairOut"] | null;
            /**
             * Refused
             * @description why this pair was refused; null when it was accepted
             */
            refused: string | null;
            resolution: components["schemas"]["Resolution"];
            /** Symbol */
            symbol: string;
        };
        /**
         * Uncovered
         * @description A stretch of the requested range the archive has never looked at.
         */
        Uncovered: {
            /**
             * From
             * Format: date-time
             */
            from: string;
            /**
             * To
             * Format: date-time
             */
            to: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx: Record<string, never>;
            /** Input */
            input: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    asset_classes_asset_classes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    candles_candles__symbol__get: {
        parameters: {
            query?: {
                resolution?: components["schemas"]["Resolution"];
                /** @description inclusive, UTC */
                from?: string | null;
                /** @description exclusive, UTC */
                to?: string | null;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandlesOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    forming_candle_candles__symbol__forming_get: {
        parameters: {
            query?: {
                /** @description omit to let the archive pick the finest live one */
                resolution?: components["schemas"]["Resolution"] | null;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormingCandleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    coverage_coverage__symbol__get: {
        parameters: {
            query?: {
                resolution?: components["schemas"]["Resolution"];
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairCoverageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deletions_deletions_get: {
        parameters: {
            query?: {
                symbol?: string | null;
                resolution?: components["schemas"]["Resolution"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairDeletionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    catalogue_indicators_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndicatorsCatalogueOut"];
                };
            };
        };
    };
    compute_indicators__symbol__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IndicatorsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndicatorsOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    catalogue_instruments_get: {
        parameters: {
            query?: {
                max_nodes?: number | null;
                asset_class?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_instruments_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jobs_jobs_get: {
        parameters: {
            query?: {
                symbol?: string | null;
                resolution?: components["schemas"]["Resolution"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPairViewOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    estimate_pairs_jobs_estimate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EstimateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEstimateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pairs_pairs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackedPairOut"][];
                };
            };
        };
    };
    track_pairs_pairs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackPairRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackPairsResult"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    delete_pair_pairs__symbol__delete: {
        parameters: {
            query?: {
                resolution?: components["schemas"]["Resolution"];
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairDeletionOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ping_ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    issue_stream_ticket_stream_tickets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamTicketOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
