/**
 * GENERATED — do not edit. Rewrite it with `pnpm contract:generate`.
 *
 * The source is teams' own OpenAPI document, printed straight from its Pydantic models
 * by `python -m teams.openapi`. No WebSocket here — unlike market-data's, this schema
 * is exactly what FastAPI already describes on its own.
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/revisions/{revision_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Revision By Id
         * @description The definition a run is working on, reached the way a run names it — by the id on
         *     `runs.team_revision_id` rather than by a version the watcher would first have to look
         *     up. Drawing a run against the team's *latest* revision instead would show the operator
         *     a graph the run is not running (specs/teams-runs, "Przebieg odbywa się na rewizji, nie
         *     na zespole").
         */
        get: operations["get_revision_by_id_revisions__revision_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Run
         * @description Asks a run to stop. 202, not 200: the status is written by the run itself as it
         *     unwinds, so what comes back here is the run as it was when the interruption was
         *     accepted — the operator's own view catches up through the stream or a reload.
         */
        post: operations["cancel_run_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Events
         * @description Progress as it happens, starting with where the run is now.
         *
         *     The snapshot first, then live events: a viewer that opens halfway through has to see
         *     the agents that already finished, and one that reconnects must not have to guess what
         *     it missed. Dropping the connection unsubscribes a queue and nothing else — the run
         *     holds no reference to any of this (specs/teams-runs, "Zerwanie połączenia odbierającego
         *     postęp MUST NOT przerwać przebiegu").
         */
        get: operations["run_events_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/steps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Steps
         * @description Who is waiting, who is working, who has finished and what they handed over — the
         *     same picture the progress stream carries, for a viewer that arrived late or came back
         *     (specs/teams-runs, "po ponownym otwarciu widać jego bieżący stan").
         */
        get: operations["get_run_steps_runs__run_id__steps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/tool-calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Tool Calls */
        get: operations["get_run_tool_calls_runs__run_id__tool_calls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules/{schedule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Schedule */
        get: operations["get_schedule_schedules__schedule_id__get"];
        /** Update Schedule */
        put: operations["update_schedule_schedules__schedule_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules/{schedule_id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable Schedule */
        post: operations["disable_schedule_schedules__schedule_id__disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules/{schedule_id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enable Schedule */
        post: operations["enable_schedule_schedules__schedule_id__enable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules/{schedule_id}/fires": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Schedule Fires */
        get: operations["get_schedule_fires_schedules__schedule_id__fires_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules/{schedule_id}/next-fires": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Next Fires
         * @description specs/terminal-teams-schedules, "Terminal nie liczy czasu wyzwolenia sam" — every
         *     time in the answer is rolled forward from now by this module, not the row's stored
         *     `next_fire_at`, which only reflects the last claim.
         */
        get: operations["next_fires_schedules__schedule_id__next_fires_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Teams
         * @description The whole of what a picker needs, and no definition — see `store._LATEST_REVISION`.
         */
        get: operations["list_teams_teams_get"];
        put?: never;
        /** Create Team */
        post: operations["create_team_teams_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{team_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Team */
        get: operations["get_team_teams__team_id__get"];
        put?: never;
        post?: never;
        /**
         * Archive Team
         * @description Retires the team from the catalogue. Its runs and the revisions they name stay —
         *     see `store._ARCHIVE_TEAM`.
         */
        delete: operations["archive_team_teams__team_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{team_id}/layout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Layout
         * @description Where the operator left each agent. A team with nothing saved answers with an empty
         *     layout rather than a 404 — never having been arranged is the ordinary state, and the
         *     canvas computes places from the dependencies for every agent this does not name.
         */
        get: operations["get_layout_teams__team_id__layout_get"];
        /**
         * Save Layout
         * @description Replaces the layout. Not a revision and not a change to one: this route never
         *     touches `team_revisions`, which is the whole reason the table it writes exists
         *     (specs/terminal-teams, "Przesunięcie nie jest zmianą definicji").
         *
         *     Agent keys are not checked against any revision on purpose. The canvas sends what it
         *     drew, an unsaved draft can carry an agent no revision knows yet, and a key that never
         *     becomes one is a row nobody reads.
         */
        put: operations["save_layout_teams__team_id__layout_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{team_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Revision
         * @description Appends. The previous revision is not read, not touched and not made obsolete —
         *     a run already pointing at it keeps meaning what it meant.
         */
        post: operations["save_revision_teams__team_id__revisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{team_id}/revisions/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Latest Revision
         * @description What the canvas opens on. Declared before the `{version}` route below, or FastAPI
         *     would try to parse "latest" as an int and answer 422.
         */
        get: operations["get_latest_revision_teams__team_id__revisions_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{team_id}/revisions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Revision
         * @description Including a revision of a retired team: a run points at a revision, and a trace
         *     that cannot be opened is not a trace (specs/teams-catalogue).
         */
        get: operations["get_revision_teams__team_id__revisions__version__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{team_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description Every run of this team, newest first — including runs of revisions since replaced,
         *     which is what makes two of them comparable at all.
         */
        get: operations["list_runs_teams__team_id__runs_get"];
        put?: never;
        /**
         * Start Run
         * @description Starts a run of the team's latest revision and answers immediately.
         *
         *     201 with the run, not the run's result: a team takes minutes, and a request held open
         *     for it would be a request that fails whenever the network does. What the operator
         *     watches afterwards is `/runs/{id}/events`, and what survives either way is the trace.
         */
        post: operations["start_run_teams__team_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{team_id}/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Schedules */
        get: operations["list_schedules_teams__team_id__schedules_get"];
        put?: never;
        /** Create Schedule */
        post: operations["create_schedule_teams__team_id__schedules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{team_id}/triggers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Triggers */
        get: operations["list_triggers_teams__team_id__triggers_get"];
        put?: never;
        /** Create Trigger */
        post: operations["create_trigger_teams__team_id__triggers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tools */
        get: operations["list_tools_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/triggers/{trigger_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trigger */
        get: operations["get_trigger_triggers__trigger_id__get"];
        /** Update Trigger */
        put: operations["update_trigger_triggers__trigger_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/triggers/{trigger_id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable Trigger */
        post: operations["disable_trigger_triggers__trigger_id__disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/triggers/{trigger_id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enable Trigger */
        post: operations["enable_trigger_triggers__trigger_id__enable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/triggers/{trigger_id}/fires": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trigger Fires */
        get: operations["get_trigger_fires_triggers__trigger_id__fires_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Usage
         * @description Both filters are optional and combine: no filter is everything this operator ever
         *     spent, `run_id` is one run's own bill, `team_id` is one team across its revisions.
         *
         *     A run belonging to somebody else returns nothing rather than 404 — this is an
         *     aggregate, and the difference between "no rows" and "not yours" is exactly what
         *     specs/teams-browser-access says a stranger must not be able to tell.
         */
        get: operations["get_usage_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentDefinition
         * @description One role inside a team: what it is told, which model answers for it, and which
         *     tools it may reach for.
         */
        AgentDefinition: {
            /**
             * Guidance
             * @default
             */
            guidance: string;
            /** Key */
            key: string;
            /** Model Id */
            model_id: string;
            /** Prompt */
            prompt: string;
            /** Role */
            role: string;
            /** Tools */
            tools?: string[];
        };
        /**
         * AgentPlace
         * @description One agent's place on the canvas — the definition's own key and two coordinates.
         *
         *     Its own shape rather than a field on `AgentDefinition`, and that is the decision
         *     rather than an accident: a definition is immutable once saved and is what a run points
         *     at, so a coordinate inside it would mint a revision every time a node was dragged
         *     (design.md, "Rozmieszczenie agentów obok rewizji, nie w niej").
         */
        AgentPlace: {
            /** Agent Key */
            agent_key: string;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * CostLimits
         * @description Budgets a revision may carry — specs/teams-usage, 'Przekroczenie granicy kosztu
         *     zatrzymuje przebieg'. Strings, like every other cost on this contract's wire: nothing
         *     here computes with these, only compares them against a running total, and a string
         *     round-trips exactly where a float would invite rescaling it should never do.
         */
        CostLimits: {
            /**
             * Daily Limit
             * @description max cost per day for this team
             */
            daily_limit?: string | null;
            /**
             * Run Limit
             * @description max cost for one run
             */
            run_limit?: string | null;
        };
        /** CreateTeamIn */
        CreateTeamIn: {
            definition: components["schemas"]["TeamDefinition"];
            /**
             * Description
             * @default
             */
            description: string;
            /** Name */
            name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail: components["schemas"]["ValidationError"][];
        };
        /**
         * ModelOut
         * @description One entry of the model catalogue — everything a picker needs and nothing else
         *     (specs/teams-models, "Katalog modeli wystarcza do zbudowania wybieraka"). The
         *     terminal MUST NOT carry a model id of its own, so a model added to this module's
         *     configuration reaches the picker with no terminal change at all.
         */
        ModelOut: {
            /** Cost Rank */
            cost_rank: number;
            /** Display Name */
            display_name: string;
            /** Id */
            id: string;
            /** Input Rate Per 1M */
            input_rate_per_1m: string;
            /** Output Rate Per 1M */
            output_rate_per_1m: string;
        };
        /**
         * NextFiresOut
         * @description specs/terminal-teams-schedules, "Terminal nie liczy czasu wyzwolenia sam" — the
         *     module's own answer to "when does this schedule fire next", computed fresh from
         *     `cron_expression` rather than read off the row's own `next_fire_at` — which reflects
         *     the last *claim*, not a live forecast, and goes stale the moment a schedule is
         *     disabled.
         */
        NextFiresOut: {
            /** Times */
            times: string[];
        };
        /** RunOut */
        RunOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: number;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
            /** Stopped Reason */
            stopped_reason: string | null;
            /** Team Revision Id */
            team_revision_id: number;
        };
        /** RunStepOut */
        RunStepOut: {
            /** Agent Key */
            agent_key: string;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: number;
            /** Output */
            output: string | null;
            /** Rounds */
            rounds: number;
            /** Run Id */
            run_id: number;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
        };
        /**
         * SaveLayoutIn
         * @description The whole layout at once, replacing what was stored. A patch per node would need
         *     the module to know which agents still exist, and the canvas already does.
         */
        SaveLayoutIn: {
            /** Places */
            places: components["schemas"]["AgentPlace"][];
        };
        /** SaveRevisionIn */
        SaveRevisionIn: {
            definition: components["schemas"]["TeamDefinition"];
        };
        /**
         * ScheduleFireOut
         * @description One fire attempt from either source, including one that started nothing
         *     (specs/teams-schedules, "Wyzwolenie bez przebiegu zostawia zapisany powód"). Exactly
         *     one of `schedule_id`/`trigger_id` is set, mirroring the row's own CHECK constraint.
         */
        ScheduleFireOut: {
            /**
             * Fired At
             * Format: date-time
             */
            fired_at: string;
            /** Id */
            id: number;
            /** Outcome */
            outcome: string;
            /** Reason */
            reason: string | null;
            /** Run Id */
            run_id: number | null;
            /** Schedule Id */
            schedule_id: number | null;
            /** Skipped Count */
            skipped_count: number;
            /** Trigger Id */
            trigger_id: number | null;
        };
        /**
         * ScheduleIn
         * @description What an operator submits to create or edit a schedule.
         */
        ScheduleIn: {
            /** Cron Expression */
            cron_expression: string;
            /** Pinned Revision Id */
            pinned_revision_id?: number | null;
            /**
             * Revision Mode
             * @default pinned
             * @enum {string}
             */
            revision_mode: "pinned" | "latest";
            /**
             * Unattended Ack
             * @default false
             */
            unattended_ack: boolean;
        };
        /** ScheduleOut */
        ScheduleOut: {
            /** Consecutive Failures */
            consecutive_failures: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Cron Expression */
            cron_expression: string;
            /** Disabled Reason */
            disabled_reason: string | null;
            /** Enabled */
            enabled: boolean;
            /** Id */
            id: number;
            /**
             * Next Fire At
             * Format: date-time
             */
            next_fire_at: string;
            /** Pinned Revision Id */
            pinned_revision_id: number | null;
            /** Revision Mode */
            revision_mode: string;
            /** Team Id */
            team_id: number;
            /** Unattended Ack */
            unattended_ack: boolean;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TeamDefinition
         * @description The whole of what a team revision carries — every agent, every dependency between
         *     them, and the cost limits a run against this revision must respect. One immutable
         *     blob per revision (specs/teams-catalogue, "Rewizja raz zapisana się nie zmienia").
         */
        TeamDefinition: {
            /** Agents */
            agents: components["schemas"]["AgentDefinition"][];
            /** Edges */
            edges?: components["schemas"]["TeamEdge"][];
            limits?: components["schemas"]["CostLimits"];
        };
        /**
         * TeamEdge
         * @description One dependency: `to` waits for `from_` and receives its output — specs/teams-runs,
         *     'Agent widzi wypowiedzi poprzedników, a nie całą historię przebiegu'.
         */
        TeamEdge: {
            /** From */
            from: string;
            /** To */
            to: string;
        };
        /**
         * TeamLayoutOut
         * @description Where the operator left each agent. Absent keys are not an error and not a zero:
         *     the canvas computes a place from the dependencies for anything this does not name
         *     (specs/terminal-teams, "Agent bez zapamiętanego miejsca").
         */
        TeamLayoutOut: {
            /** Places */
            places: components["schemas"]["AgentPlace"][];
        };
        /**
         * TeamOut
         * @description A row in the catalogue — specs/teams-catalogue, "Katalog wystarcza, żeby wybrać
         *     zespół bez otwierania go". No `owner_principal` on the wire: ownership gates which
         *     rows a query returns at all (specs/teams-browser-access), the same way agent's own
         *     `SessionOut` never carries one either.
         */
        TeamOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string;
            /** Id */
            id: number;
            /** Latest Revision */
            latest_revision: number;
            /** Name */
            name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TeamRevisionOut */
        TeamRevisionOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            definition: components["schemas"]["TeamDefinition"];
            /** Id */
            id: number;
            /** Team Id */
            team_id: number;
            /** Version */
            version: number;
        };
        /** ToolCallOut */
        ToolCallOut: {
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Ms */
            duration_ms: number;
            /** Id */
            id: number;
            /** Outcome */
            outcome: string;
            /** Position */
            position: number;
            /** Result Text */
            result_text: string;
            /** Round Index */
            round_index: number;
            /** Run Step Id */
            run_step_id: number;
            /** Tool Name */
            tool_name: string;
        };
        /**
         * ToolOut
         * @description One tool as the tool server announces it right now (specs/teams-tool-access,
         *     "Moduł nie trzyma kopii tego, co ogłasza serwer narzędzi").
         *
         *     Name and description, and deliberately not the input schema: a definition points at a
         *     tool by name and carries nothing else about it, so the picker needs a label and a line
         *     of prose. Publishing the schema would put a copy of somebody else's contract on this
         *     module's wire, where it would be stale from the first argument market-mcp renames.
         */
        ToolOut: {
            /** Description */
            description: string;
            /** Name */
            name: string;
        };
        /**
         * TriggerIn
         * @description A market condition, expressed as a call to a tool this module already has a
         *     session for (specs/teams-triggers, "Warunek jest czytany narzędziami serwera
         *     narzędzi") — never a locally computed indicator. `field_path` names the value inside
         *     that call's result to compare; `threshold` is a string for the same reason every
         *     other number on this contract that a caller must not rescale is (see `CostLimits`).
         */
        TriggerIn: {
            /** Arguments */
            arguments?: {
                [key: string]: unknown;
            };
            /**
             * Comparison
             * @enum {string}
             */
            comparison: "gt" | "gte" | "lt" | "lte" | "eq";
            /**
             * Cooldown Seconds
             * @default 900
             */
            cooldown_seconds: number;
            /** Field Path */
            field_path: string;
            /** Pinned Revision Id */
            pinned_revision_id?: number | null;
            /**
             * Poll Interval Seconds
             * @default 300
             */
            poll_interval_seconds: number;
            /**
             * Revision Mode
             * @default pinned
             * @enum {string}
             */
            revision_mode: "pinned" | "latest";
            /** Threshold */
            threshold: string;
            /** Tool Name */
            tool_name: string;
            /**
             * Unattended Ack
             * @default false
             */
            unattended_ack: boolean;
        };
        /** TriggerOut */
        TriggerOut: {
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Comparison */
            comparison: string;
            /** Consecutive Failures */
            consecutive_failures: number;
            /** Cooldown Seconds */
            cooldown_seconds: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Disabled Reason */
            disabled_reason: string | null;
            /** Enabled */
            enabled: boolean;
            /** Field Path */
            field_path: string;
            /** Id */
            id: number;
            /** Last Checked At */
            last_checked_at: string | null;
            /** Last Fired At */
            last_fired_at: string | null;
            /** Last Result */
            last_result: boolean | null;
            /**
             * Next Check At
             * Format: date-time
             */
            next_check_at: string;
            /** Pinned Revision Id */
            pinned_revision_id: number | null;
            /** Poll Interval Seconds */
            poll_interval_seconds: number;
            /** Revision Mode */
            revision_mode: string;
            /** Team Id */
            team_id: number;
            /** Threshold */
            threshold: string;
            /** Tool Name */
            tool_name: string;
            /** Unattended Ack */
            unattended_ack: boolean;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** UsageAggregateOut */
        UsageAggregateOut: {
            /** Cost */
            cost: string;
            /** Input Tokens */
            input_tokens: number;
            /** Key */
            key: string;
            /** Output Tokens */
            output_tokens: number;
            /** Unknown Count */
            unknown_count: number;
        };
        /**
         * UsageSummaryOut
         * @description specs/teams-usage, "Odczyt zużycia w rozbiciu na role" — `by_agent` is the read
         *     that requirement is for; `by_model` is agent's own `UsageSummaryOut` precedent,
         *     kept because a run can genuinely mix cheap and expensive models across agents.
         */
        UsageSummaryOut: {
            /** By Agent */
            by_agent: components["schemas"]["UsageAggregateOut"][];
            /** By Model */
            by_model: components["schemas"]["UsageAggregateOut"][];
            /** Total Cost */
            total_cost: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx: Record<string, never>;
            /** Input */
            input: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_models_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelOut"][];
                };
            };
        };
    };
    get_revision_by_id_revisions__revision_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revision_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamRevisionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_events_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_steps_runs__run_id__steps_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStepOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_tool_calls_runs__run_id__tool_calls_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolCallOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schedule_schedules__schedule_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                schedule_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_schedule_schedules__schedule_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                schedule_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disable_schedule_schedules__schedule_id__disable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                schedule_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enable_schedule_schedules__schedule_id__enable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                schedule_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schedule_fires_schedules__schedule_id__fires_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                schedule_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleFireOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    next_fires_schedules__schedule_id__next_fires_get: {
        parameters: {
            query?: {
                count?: number;
            };
            header?: never;
            path: {
                schedule_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NextFiresOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_teams_teams_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamOut"][];
                };
            };
        };
    };
    create_team_teams_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTeamIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_team_teams__team_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_team_teams__team_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_layout_teams__team_id__layout_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamLayoutOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_layout_teams__team_id__layout_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveLayoutIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamLayoutOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_revision_teams__team_id__revisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveRevisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamRevisionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_revision_teams__team_id__revisions_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamRevisionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_revision_teams__team_id__revisions__version__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: number;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamRevisionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_teams__team_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_teams__team_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_schedules_teams__team_id__schedules_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_schedule_teams__team_id__schedules_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_triggers_teams__team_id__triggers_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_trigger_teams__team_id__triggers_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TriggerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tools_tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolOut"][];
                };
            };
        };
    };
    get_trigger_triggers__trigger_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trigger_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_trigger_triggers__trigger_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trigger_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TriggerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disable_trigger_triggers__trigger_id__disable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trigger_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enable_trigger_triggers__trigger_id__enable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trigger_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trigger_fires_triggers__trigger_id__fires_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trigger_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleFireOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_usage_usage_get: {
        parameters: {
            query?: {
                run_id?: number | null;
                team_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
