/**
 * GENERATED — do not edit. Rewrite it with `pnpm contract:generate`.
 *
 * The source is market-data's own OpenAPI document, printed straight from its Pydantic
 * models by `python -m market_data.openapi`. Everything the terminal reads off that
 * module's wire — including the subscription's Snapshot and CandleChange, which have no
 * HTTP path — is described here, so `tsc` is what notices a contract change rather than
 * an operator noticing a blank cell.
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candles/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Candles for one pair over a time range
         * @description Answers with the series and, separately, the stretches of the requested range the archive never verified. Those are not the same as periods with no candle: a closed market has no candle either, and only one of the two is missing data.
         *
         *     Resolutions between MINUTE_5 and HOUR_4 are computed from the minute series rather than collected separately — the provider serves 1000 candles per request at ten requests a second, so fetching each one costs its own traffic for data the finest already implies. MINUTE, DAY and WEEK come from the provider: a daily boundary follows the venue's session, not the clock.
         */
        get: operations["candles_candles__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coverage/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What the archive has verified for one pair */
        get: operations["coverage_coverage__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deletions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recorded deletions, newest first */
        get: operations["deletions_deletions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Whether the archive can answer at all, which means whether its database can.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Collection jobs, one row per pair they touched */
        get: operations["jobs_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Price a collection job without creating it
         * @description Runs the exact planning a job creation would, without writing anything: no pair is tracked, no job exists afterwards. A symbol the gateway does not know comes back marked `unknown` rather than failing the whole estimate.
         */
        post: operations["estimate_pairs_jobs_estimate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One job, whole — every pair and every chunk it covers */
        get: operations["job_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry a job's failed or interrupted chunks
         * @description Resets only chunks left `failed` or `interrupted`, as a new attempt of the same job — never a new job, and never a chunk already `done`. Refused with 409 when there is nothing to retry.
         */
        post: operations["retry_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pairs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Which pairs are collected, and whether collection is happening */
        get: operations["pairs_pairs_get"];
        put?: never;
        /**
         * Start collecting one or more pairs
         * @description Each pair is validated against the gateway independently, so one refusal — an unknown symbol, the tracked-pairs ceiling — never withholds the pairs that were fine. Accepting at least one pair that needed history behind it starts a collection job and returns its id; a request whose pairs were all already fully covered accepts them with no job. The original single-pair shape (`symbol`, `resolution`) still works and still means the configured default depth.
         */
        post: operations["track_pairs_pairs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pairs/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Stop collecting a pair and delete its data
         * @description Stops collection, releases the provider connection, and removes every candle and coverage range this pair holds — irreversibly. A symbol whose minute series is deleted also loses the rollups computed from it. 404 for a pair not currently tracked, which deletes nothing.
         */
        delete: operations["delete_pair_pairs__symbol__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Candle
         * @description One candle, identified by symbol, resolution and the start of its period.
         *
         *     Edges are optional because the gateway's are: the provider occasionally omits one,
         *     and a candle with a missing edge is still better evidence than no candle at all.
         */
        Candle: {
            /**
             * Close
             * @default null
             */
            close: number | null;
            /**
             * Forming
             * @default false
             */
            forming: boolean;
            /**
             * High
             * @default null
             */
            high: number | null;
            /**
             * Low
             * @default null
             */
            low: number | null;
            /**
             * Open
             * @default null
             */
            open: number | null;
            /**
             * Period Start
             * Format: date-time
             */
            period_start: string;
            /** @default bid */
            price_side: components["schemas"]["PriceSide"];
            resolution: components["schemas"]["Resolution"];
            source: components["schemas"]["CandleSource"];
            /** Symbol */
            symbol: string;
            /**
             * Volume
             * @default null
             */
            volume: number | null;
        };
        /**
         * CandleChange
         * @description One candle, closed or still forming, said explicitly.
         *
         *     One message kind for both, marked rather than split, because a consumer upserts by
         *     period start and two message types would only make it reconcile them itself. The mark
         *     is what stops a chart treating a period still moving as settled.
         */
        CandleChange: {
            candle: components["schemas"]["Candle"];
            /**
             * Kind
             * @default candle
             * @constant
             */
            kind: "candle";
            resolution: components["schemas"]["Resolution"];
            /** Symbol */
            symbol: string;
        };
        /**
         * CandleOut
         * @description One settled candle. No `forming`: everything in a range read has closed.
         */
        CandleOut: {
            /** Close */
            close: number | null;
            /** High */
            high: number | null;
            /** Low */
            low: number | null;
            /** Open */
            open: number | null;
            /**
             * Time
             * Format: date-time
             * @description the start of the candle's period, UTC
             */
            time: string;
            /** Volume */
            volume: number | null;
        };
        /**
         * CandleSource
         * @description Which way a candle reached the archive.
         *
         *     Kept because the two are not equally trustworthy: a stream that was disconnected
         *     misses quotes and understates a candle's range, while a history read sees the period
         *     whole. Which one wins is decided by the archive, and it cannot decide without this.
         * @enum {string}
         */
        CandleSource: "history" | "stream";
        /**
         * CandlesOut
         * @description A range read, and everything needed to know what it is not saying.
         *
         *     `uncovered` is the part that matters and the part a plain list of candles cannot
         *     express. An empty series over a weekend and an empty series because ingest was down
         *     are the same list; only one of them is the whole story.
         */
        CandlesOut: {
            /** Candles */
            candles: components["schemas"]["CandleOut"][];
            /**
             * Derived
             * @description true when the series was computed from the minute series rather than collected at this resolution
             */
            derived: boolean;
            /** @description which side of the spread these are built from; the archive holds bid */
            price_side: components["schemas"]["PriceSide"];
            resolution: components["schemas"]["Resolution"];
            /** Symbol */
            symbol: string;
            /**
             * Uncovered
             * @description stretches of the requested range the archive never verified
             */
            uncovered: components["schemas"]["Uncovered"][];
        };
        /** ChunkOut */
        ChunkOut: {
            /** Attempt */
            attempt: number;
            /** Candles Written */
            candles_written: number;
            /**
             * Chunk End
             * Format: date-time
             */
            chunk_end: string;
            /**
             * Chunk Start
             * Format: date-time
             */
            chunk_start: string;
            /** Failure */
            failure: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: number;
            /** Requests */
            requests: number;
            resolution: components["schemas"]["Resolution"];
            /** Started At */
            started_at: string | null;
            state: components["schemas"]["ChunkState"];
            /** Symbol */
            symbol: string;
        };
        /**
         * ChunkState
         * @description One chunk's life. `interrupted` is reached only from `pending` or `running`, and
         *     only by this module's own startup — no runner survives a restart, so anything not
         *     yet settled at that moment was orphaned, not merely delayed.
         * @enum {string}
         */
        ChunkState: "pending" | "running" | "done" | "failed" | "skipped" | "interrupted";
        /**
         * CollectionState
         * @description Whether data is actually arriving, as far as the archive can tell.
         *
         *     Being on the list proves nothing. A subscription can die without a sound, and the
         *     only visible symptom is a series that stops growing while the market is open.
         * @enum {string}
         */
        CollectionState: "never_collected" | "collecting" | "stalled" | "market_closed" | "unknown";
        /** CoverageOut */
        CoverageOut: {
            /**
             * From
             * Format: date-time
             */
            from: string;
            /**
             * History Ended
             * @description true when the provider has nothing older than `from`
             */
            history_ended: boolean;
            /**
             * To
             * Format: date-time
             */
            to: string;
        };
        /** EstimateRequest */
        EstimateRequest: {
            /**
             * Collect From
             * Format: date-time
             * @description moment history should reach back to
             */
            collect_from: string;
            /** Pairs */
            pairs: components["schemas"]["PairRequest"][];
        };
        /**
         * FillOut
         * @description What this pair's most recent backfill did, and what it cost.
         *
         *     A fill can run for tens of minutes and fail on one pair while the others carry on, so
         *     where it got to is part of what is being asked when somebody asks what is collected —
         *     not something to go and read a log for. `summary` is the same one line the module
         *     logs, so an operator comparing the two is comparing one sentence with itself.
         */
        FillOut: {
            /**
             * Failure
             * @description why it failed, named; null when it did not
             */
            failure: string | null;
            /**
             * Finished At
             * @description when this fill ended; null while it is still running
             */
            finished_at: string | null;
            /**
             * Requested
             * @description candles asked of the gateway; 0 means nothing was asked
             */
            requested: number;
            /**
             * Requests
             * @description provider calls the gateway made behind that one request
             * @default 0
             */
            requests: number;
            /**
             * Summary
             * @description the whole outcome as one line, for a person
             */
            summary: string;
            /**
             * Written
             * @description rows the archive took, which is not always how many arrived — a streamed value never displaces a stored history one
             * @default 0
             */
            written: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail: components["schemas"]["ValidationError"][];
        };
        /** JobEstimateOut */
        JobEstimateOut: {
            /** Pairs */
            pairs: components["schemas"]["PairEstimateOut"][];
            /** Total Estimated Bytes */
            total_estimated_bytes: number;
            /** Total Estimated Candles */
            total_estimated_candles: number;
        };
        /**
         * JobOut
         * @description A whole job — every pair it touched. What `GET /jobs/{id}` and
         *     `POST /jobs/{id}/retry` answer with; `GET /jobs` answers with `JobPairViewOut`.
         */
        JobOut: {
            /** Attempt */
            attempt: number;
            /** Candles Written */
            candles_written: number;
            /** Chunks */
            chunks: components["schemas"]["ChunkOut"][];
            /** Chunks Done */
            chunks_done: number;
            /** Chunks Total */
            chunks_total: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /**
             * Requested From
             * Format: date-time
             */
            requested_from: string;
            running_pair: components["schemas"]["RunningPair"] | null;
            status: components["schemas"]["JobStatus"];
        };
        /**
         * JobPairViewOut
         * @description One job, narrowed to one pair — what `GET /jobs` answers with.
         */
        JobPairViewOut: {
            /** Attempt */
            attempt: number;
            /** Candles Written */
            candles_written: number;
            /** Chunks */
            chunks: components["schemas"]["ChunkOut"][];
            /** Chunks Done */
            chunks_done: number;
            /** Chunks Total */
            chunks_total: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Job Id */
            job_id: number;
            /**
             * Requested From
             * Format: date-time
             */
            requested_from: string;
            resolution: components["schemas"]["Resolution"];
            status: components["schemas"]["JobStatus"];
            /** Symbol */
            symbol: string;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "running" | "succeeded" | "partial" | "failed" | "interrupted";
        /** PairCoverageOut */
        PairCoverageOut: {
            /**
             * Earliest Reachable
             * @description the oldest moment worth asking the provider about; null means the end of its history has not been reached, not that there is no limit
             */
            earliest_reachable: string | null;
            /** Ranges */
            ranges: components["schemas"]["CoverageOut"][];
            resolution: components["schemas"]["Resolution"];
            /** Symbol */
            symbol: string;
        };
        /**
         * PairDeletionOut
         * @description What `DELETE /pairs/{symbol}` and `GET /deletions` answer with — the trace of one
         *     skasowanie, kept after the data itself is gone.
         */
        PairDeletionOut: {
            /**
             * Candles Removed
             * @description how many candles were removed; 0 is a valid count
             */
            candles_removed: number;
            /**
             * Deleted At
             * Format: date-time
             */
            deleted_at: string;
            /**
             * Removed From
             * @description the oldest removed candle's period; null together with `removed_to` when the pair had never collected anything
             */
            removed_from: string | null;
            /**
             * Removed To
             * @description the newest removed candle's period; null with `removed_from`
             */
            removed_to: string | null;
            resolution: components["schemas"]["Resolution"];
            /** Symbol */
            symbol: string;
        };
        /** PairEstimateOut */
        PairEstimateOut: {
            /**
             * Clipped
             * @description true when `effective_from` differs from `collect_from`
             * @default false
             */
            clipped: boolean;
            /**
             * Effective From
             * @description what `collect_from` was actually clipped to; null when the symbol is unknown to the gateway
             */
            effective_from: string | null;
            /**
             * Estimated Bytes
             * @default 0
             */
            estimated_bytes: number;
            /**
             * Estimated Candles
             * @default 0
             */
            estimated_candles: number;
            resolution: components["schemas"]["Resolution"];
            /** Symbol */
            symbol: string;
            /**
             * Unknown
             * @description true when the gateway does not know this symbol
             * @default false
             */
            unknown: boolean;
        };
        /** PairRequest */
        PairRequest: {
            /**
             * @default MINUTE
             * @example MINUTE
             */
            resolution: components["schemas"]["Resolution"];
            /**
             * Symbol
             * @example US100
             */
            symbol: string;
        };
        /**
         * PriceSide
         * @description Which side of the spread a candle is built from.
         *
         *     Everything stored today is `BID`, the side the gateway builds both its history and
         *     its stream from. The value is written next to the data anyway, so that adding the
         *     other side one day is a schema change with a visible cost rather than two series
         *     quietly averaged into one.
         * @enum {string}
         */
        PriceSide: "bid" | "ask";
        /**
         * Problem
         * @description A refusal that names itself.
         *
         *     Never a database error and never a credential — there is no credential on this path to
         *     leak, and a raw `asyncpg` message tells a consumer nothing it can act on while telling
         *     anyone reading the logs more about the schema than they need.
         */
        Problem: {
            /** Detail */
            detail: string;
        };
        /**
         * Resolution
         * @description Candle time frame — the gateway's vocabulary, spelled its way.
         * @enum {string}
         */
        Resolution: "MINUTE" | "MINUTE_5" | "MINUTE_15" | "MINUTE_30" | "HOUR" | "HOUR_4" | "DAY" | "WEEK";
        /** RunningPair */
        RunningPair: {
            resolution: components["schemas"]["Resolution"];
            /** Symbol */
            symbol: string;
        };
        /**
         * Snapshot
         * @description The first message on every subscription, and the only one that looks backwards.
         *
         *     Carries the settled series and, separately, whatever period is currently being built.
         *     They are separate because they mean different things: one will never change again, the
         *     other changes with every quote.
         */
        Snapshot: {
            /** Candles */
            candles: components["schemas"]["Candle"][];
            /** @default null */
            forming: components["schemas"]["Candle"] | null;
            /**
             * Kind
             * @default snapshot
             * @constant
             */
            kind: "snapshot";
            resolution: components["schemas"]["Resolution"];
            /** Symbol */
            symbol: string;
        };
        /**
         * TrackPairRequest
         * @description Body for `POST /pairs`.
         *
         *     Two shapes, never mixed: the original single-pair one (`symbol`, `resolution`,
         *     still meaning exactly what it always did — no `collect_from` is the default depth)
         *     and a multi-pair one (`pairs`, `collect_from`) for adding several pairs as one
         *     decision. A consumer that has never heard of `pairs` keeps working unchanged.
         */
        TrackPairRequest: {
            /**
             * Collect From
             * @description moment history should reach back to; omitted means the configured default depth, exactly as before this field existed
             */
            collect_from?: string | null;
            /**
             * Pairs
             * @description multiple pairs added as one decision; excludes `symbol`
             */
            pairs?: components["schemas"]["PairRequest"][] | null;
            /**
             * @default MINUTE
             * @example MINUTE
             */
            resolution: components["schemas"]["Resolution"];
            /**
             * Symbol
             * @example US100
             */
            symbol?: string | null;
        };
        /** TrackPairsResult */
        TrackPairsResult: {
            /**
             * Job Id
             * @description the backfill job covering the accepted pairs, or null when nothing needed fetching
             */
            job_id: number | null;
            /** Results */
            results: components["schemas"]["TrackedPairResult"][];
        };
        /** TrackedPairOut */
        TrackedPairOut: {
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
            /**
             * Collect From
             * Format: date-time
             * @description the moment history for this pair is meant to reach back to
             */
            collect_from: string;
            /** @description whether data is actually arriving, as far as the archive can tell */
            collection: components["schemas"]["CollectionState"];
            /**
             * Earliest Candle
             * @description the oldest period collected — how far back the data actually reaches, which is not `collect_from` (where it was asked to reach) — or null if none yet
             */
            earliest_candle: string | null;
            /** @description the pair's most recent backfill, or null if none has run since the module started — fills live in memory and do not survive a restart */
            last_fill: components["schemas"]["FillOut"] | null;
            /**
             * Latest Candle
             * @description the newest period collected, or null if none yet
             */
            latest_candle: string | null;
            resolution: components["schemas"]["Resolution"];
            /** Symbol */
            symbol: string;
        };
        /**
         * TrackedPairResult
         * @description One pair's outcome from `POST /pairs` — never a bare list of pairs, because a
         *     refusal for one must not be indistinguishable from silence about it.
         */
        TrackedPairResult: {
            /** @description present when this pair was accepted */
            pair: components["schemas"]["TrackedPairOut"] | null;
            /**
             * Refused
             * @description why this pair was refused; null when it was accepted
             */
            refused: string | null;
            resolution: components["schemas"]["Resolution"];
            /** Symbol */
            symbol: string;
        };
        /**
         * Uncovered
         * @description A stretch of the requested range the archive has never looked at.
         */
        Uncovered: {
            /**
             * From
             * Format: date-time
             */
            from: string;
            /**
             * To
             * Format: date-time
             */
            to: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx: Record<string, never>;
            /** Input */
            input: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    candles_candles__symbol__get: {
        parameters: {
            query?: {
                resolution?: components["schemas"]["Resolution"];
                /** @description inclusive, UTC */
                from?: string | null;
                /** @description exclusive, UTC */
                to?: string | null;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandlesOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    coverage_coverage__symbol__get: {
        parameters: {
            query?: {
                resolution?: components["schemas"]["Resolution"];
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairCoverageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deletions_deletions_get: {
        parameters: {
            query?: {
                symbol?: string | null;
                resolution?: components["schemas"]["Resolution"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairDeletionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    jobs_jobs_get: {
        parameters: {
            query?: {
                symbol?: string | null;
                resolution?: components["schemas"]["Resolution"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPairViewOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    estimate_pairs_jobs_estimate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EstimateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEstimateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pairs_pairs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackedPairOut"][];
                };
            };
        };
    };
    track_pairs_pairs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackPairRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackPairsResult"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    delete_pair_pairs__symbol__delete: {
        parameters: {
            query?: {
                resolution?: components["schemas"]["Resolution"];
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairDeletionOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}

// DELIBERATE BREAK
