"""Reading and writing everything `teams` owns, through asyncpg and no ORM, as a package since it reached 1,227 lines.
The owner filter is part of every statement rather than of the routes, so a stranger's row answers as a missing one."""

from __future__ import annotations

from .catalogue import (
    archive_team,
    create_team,
    get_latest_revision,
    get_revision,
    get_revision_by_id,
    get_team,
    list_teams,
    save_revision,
)
from .fires import (
    latest_run_status_for_schedule,
    latest_run_status_for_trigger,
    list_fires_for_schedule,
    list_fires_for_trigger,
    record_fire,
)
from .layout import get_layout, save_layout
from .memory import (
    add_memory,
    count_memories_for_run,
    delete_memory,
    list_memories,
)
from .runs import (
    create_run,
    fail_running_steps,
    fail_unfinished_runs,
    finish_run,
    finish_step,
    get_run,
    get_run_status,
    get_run_steps,
    get_run_tool_calls,
    list_runs_for_team,
    mark_run_running,
    record_tool_call,
    start_step,
)
from .schedules import (
    claim_due_schedule,
    create_schedule,
    delete_schedule,
    disable_schedule_for_failures,
    get_schedule,
    increment_schedule_failures,
    list_due_schedules,
    list_schedules_for_team,
    reset_schedule_failures,
    set_schedule_enabled,
    update_schedule,
)
from .trades import get_run_trades, record_trade, settle_trade, team_trades_since
from .triggers import (
    claim_trigger_for_check,
    create_trigger,
    delete_trigger,
    disable_trigger_for_failures,
    get_trigger,
    increment_trigger_failures,
    list_due_triggers,
    list_triggers_for_team,
    record_trigger_check,
    reset_trigger_failures,
    set_trigger_enabled,
    update_trigger,
)
from .usage import (
    record_usage,
    team_cost_since,
    usage_by_agent,
    usage_by_model,
    usage_total_cost,
)

__all__ = [
    "add_memory",
    "archive_team",
    "claim_due_schedule",
    "claim_trigger_for_check",
    "count_memories_for_run",
    "create_run",
    "create_schedule",
    "create_team",
    "create_trigger",
    "delete_memory",
    "delete_schedule",
    "delete_trigger",
    "disable_schedule_for_failures",
    "disable_trigger_for_failures",
    "fail_running_steps",
    "fail_unfinished_runs",
    "finish_run",
    "finish_step",
    "get_latest_revision",
    "get_layout",
    "get_revision",
    "get_revision_by_id",
    "get_run",
    "get_run_status",
    "get_run_steps",
    "get_run_tool_calls",
    "get_run_trades",
    "get_schedule",
    "get_team",
    "get_trigger",
    "increment_schedule_failures",
    "increment_trigger_failures",
    "latest_run_status_for_schedule",
    "latest_run_status_for_trigger",
    "list_due_schedules",
    "list_due_triggers",
    "list_fires_for_schedule",
    "list_fires_for_trigger",
    "list_memories",
    "list_runs_for_team",
    "list_schedules_for_team",
    "list_teams",
    "list_triggers_for_team",
    "mark_run_running",
    "record_fire",
    "record_tool_call",
    "record_trade",
    "record_trigger_check",
    "record_usage",
    "reset_schedule_failures",
    "reset_trigger_failures",
    "save_layout",
    "save_revision",
    "set_schedule_enabled",
    "set_trigger_enabled",
    "settle_trade",
    "start_step",
    "team_cost_since",
    "team_trades_since",
    "update_schedule",
    "update_trigger",
    "usage_by_agent",
    "usage_by_model",
    "usage_total_cost",
]
